ibmruntimes/openj9-openjdk-jdk

closed/autoconf/custom-spec.gmk.in

Remove workaround for openj9#1522 fix

---

test/jdk/TEST.ROOT

Fix TEST.ROOT

---

closed/src/java.rmi/share/classes/module-info.java.extra

Fixup module-info.java.extra

---

closed/autoconf/custom-hook.m4

Find correct build version tag

---

closed/OpenJ9.gmk

See https://github.com/eclipse/openj9/issues/2100.

Copy test executables to images/test/openj9

---

closed/make/launcher/Launcher-jdk.jcmd-post.gmk

Fixes https://github.com/ibmruntimes/openj9-openjdk-jdk/issues/16.

Suppress building unsupported executables

---

closed/OpenJ9.gmk

Signed-off-by: Keith W. Campbell <keithc@ca.ibm.com>

Fix spelling of openj9.dtfj

---

.copyrightignore

Add .copyrightignore for use by copyrightChecker

---

buildenv/jenkins/jobs/infrastructure/copyrightCheck

Change check for where IBM copyright is located

---

.copyrightignore
buildenv/jenkins/jobs/infrastructure/copyrightCheck

Update copyrightCheck to handle LICENSE file

---

closed/autoconf/custom-hook.m4

Depends on eclipse/openj9#3995.

Enable ddr by default on aix

---

src/java.base/share/native/libfdlibm/k_rem_pio2.c

* file was otherwise unchanged relative to openjdk

Remove IBM copyright notice

---

buildenv/jenkins/jobs/infrastructure/copyrightCheckDir.groovy
buildenv/jenkins/jobs/infrastructure/copyrightCheckDir.sh

Create scripts to check copyright headers in extensions repos

---

buildenv/jenkins/jobs/infrastructure/copyrightCheckDir.sh

Fix erroneous reporting of copyright errors

---

closed/autoconf/custom-hook.m4

Exclude _openj9 from java version tag search

---

buildenv/jenkins/jobs/infrastructure/copyrightCheckDir.groovy

Add clean workspace

---

closed/make/closed_make/launcher/Launcher-jdk.jcmd.gmk

Add launcher definition for jps

---

closed/test/jtreg-ext/requires/OpenJ9PropsExt.java

Signed-off-by: Ben Walsh <ben_walsh@uk.ibm.com>

Implement initial basic OpenJ9 props class

---

closed/autoconf/custom-hook.m4

* now works with a shallow clone
* also works faster

Improve git tag resolution

---

.copyrightignore

Fixes https://github.com/ibmruntimes/openj9-openjdk-jdk/issues/97

Add .project files to .copyrightignore

---

closed/src/java.base/aix/native/libjncrypto/NativeCrypto_md.c
closed/src/java.base/macosx/native/libjncrypto/NativeCrypto_md.c
closed/src/java.base/share/classes/jdk/crypto/jniprovider/NativeCrypto.java
closed/src/java.base/share/native/libjncrypto/NativeCrypto.c
closed/src/java.base/share/native/libjncrypto/NativeCrypto_md.h
closed/src/java.base/unix/native/libjncrypto/NativeCrypto_md.c
closed/src/java.base/windows/native/libjncrypto/NativeCrypto_md.c

Update OpenSSL to support v1.0.1 at runtime. Also add trace messages.

---

closed/autoconf/custom-hook.m4

Signed-off-by: Nazim Uddin Bhuiyan <Nazim.Uddin.Bhuiyan@ibm.com>

Downgrade NASM requirement to v2.11 on x86

---

closed/src/java.base/aix/native/libjncrypto/NativeCrypto_md.c
closed/src/java.base/macosx/native/libjncrypto/NativeCrypto_md.c

Fix issues with get_library_path on MacOS and AIX

---

closed/src/java.base/share/classes/com/sun/crypto/provider/NativeChaCha20Cipher.java
closed/src/java.base/share/classes/com/sun/crypto/provider/NativeCipherBlockChaining.java
closed/src/java.base/share/classes/jdk/crypto/jniprovider/NativeCrypto.java
closed/src/java.base/share/native/libjncrypto/NativeCrypto.c
src/java.base/share/classes/com/sun/crypto/provider/CipherCore.java
src/java.base/share/classes/com/sun/crypto/provider/SunJCE.java
src/java.base/share/classes/sun/security/provider/SunEntries.java
src/java.base/share/classes/sun/security/rsa/RSACore.java

* brought forward from jdk11 (ibmruntimes/openj9-openjdk-jdk11#167)

Native ChaCha20-Poly1305 implementation with OpenSSL

---

src/java.base/share/classes/com/sun/crypto/provider/SunJCE.java

* use a helper method so the field can be final

Rework static initialization of useNativeChaCha20Cipher

---

closed/OpenJ9.gmk

Associate *TraceFormat.dat files with the module openj9.traceformat

---

src/java.base/share/classes/java/util/Arrays.java

Refactor GPUAssistHolder

---

closed/make/closed_make/launcher/Launcher-jdk.jcmd.gmk

Requires https://github.com/eclipse/openj9/pull/5538

Add launcher for jmap

---

closed/OpenJ9.gmk

Fix test image rule to use correct path

---

closed/src/java.base/unix/native/libjncrypto/NativeCrypto_md.c

Add OpenSSL 1.0.x library name used on RHEL

---

closed/make/closed_make/launcher/Launcher-jdk.jcmd.gmk

Add launcher for jcmd

---

closed/src/java.base/share/classes/sun/security/provider/NativeDigest.java

Signed-off-by: Alon Shalev Housfater alonsh@ca.ibm.com
FYI @keithc-ca

Use Cleaner to free digest native context

---

closed/src/java.base/share/classes/sun/security/rsa/NativeRSACore.java
src/java.base/share/classes/sun/security/rsa/RSAPrivateCrtKeyImpl.java
src/java.base/share/classes/sun/security/rsa/RSAPublicKeyImpl.java

* add queue for rsa key
* remove synchronize for rsa operation
Signed-off-by: Chao Shan <chao.shan@ibm.com>

Modify RSA Key for multithread performance

---

closed/make/closed_make/launcher/Launcher-jdk.jcmd.gmk
src/java.base/share/classes/java/io/ObjectInputStream.java

**Add a launcher for jstat**
Added a launcher for jstat.
depends: eclipse/openj9#7240
FYI: @DanHeidinga 

Add a launcher for jstat

---

closed/src/java.base/share/classes/com/sun/crypto/provider/NativeCipherBlockChaining.java

* remove finalize
* add a Cleaner
Signed-off-by: Chao Shan <chao.shan@ibm.com>

Fix crash in NativeCrypto_CBCUpdate openssl support (issue 8181)

---

closed/OpenJ9.gmk

This is a replay of ibmruntimes/openj9-openjdk-jdk11#257 for Java next.

Use codesign as appropriate on OSX

---

closed/OpenJ9.gmk
closed/autoconf/custom-spec.gmk.in
closed/make/copy/Copy-java.base.gmk

A replay of ibmruntimes/openj9-openjdk-jdk11#261 for jdk next.
Issue: eclipse/openj9#8389

Sign bundled crypto libraries

---

src/java.base/share/classes/java/io/ObjectInputStream.java

Port from: ibmruntimes/openj9-openjdk-jdk11#260
Signed-off-by: Theresa Mammarella <Theresa.T.Mammarella@ibm.com>

Fix ludcl refresh logic

---

closed/CopySupport.gmk
closed/DebugImage.gmk
closed/custom/Main.gmk
closed/custom/copy/Copy-java.base.gmk

* copy debuginfo files for openj9 shared libraries
* collect files (*.debuginfo, *.pdb, etc.) into images/debug-image

Add debug-image target

---

src/java.base/unix/native/libjli/java_md_solinux.c

* Add malloc option if AIX
Signed-off-by: Chao Shan <chao.shan@ibm.com>

Improved AIX performance for multi-thread crypto

---

closed/CopySupport.gmk
closed/DebugImage.gmk

Part of the solution to eclipse/openj9#8821.

Always copy OpenJ9 debug information

---

closed/custom/copy/Copy-java.base.gmk
openj9-openjdk-notices

Add openj9-openjdk-notices

---

buildenv/jenkins/jobs/infrastructure/copyrightCheckDir.sh

jdk/src/solaris/native/sun/security/smartcardio/MUSCLE/COPYING

Fixed script with wrong path

---

closed/autoconf/custom-hook.m4

* 'no' disables use of cmake (the user said `--with-cmake=no` or `--without-cmake`)
* blank or 'yes' enables cmake with the default program (cmake)
* any other value is expected to name the cmake program (absolute or PATH-relative)
This is equivalent to ibmruntimes/openj9-openjdk-jdk8#388 for jdknext.

Fix handling of '--with-cmake' configure option

---

closed/autoconf/custom-hook.m4

* it is no longer required for jitserver

Stop checking for protoc

---

closed/autoconf/custom-hook.m4
closed/autoconf/toolchain-win.cmake.in

ibmruntimes/openj9-openjdk-jdk11#185
ibmruntimes/openj9-openjdk-jdk11#161
ibmruntimes/openj9-openjdk-jdk11#153
ibmruntimes/openj9-openjdk-jdk11#68

Port CMake Changes from jdk11

---

closed/autoconf/custom-hook.m4
closed/autoconf/toolchain-win.cmake.in

CMake: Generate tool wrapper for NASM on windows

---

closed/src/java.base/share/classes/com/sun/crypto/provider/NativeChaCha20Cipher.java

Fixing [OpenJ9 Issue 9079](https://github.com/eclipse/openj9/issues/9079)
Changed the `NativeChaCha20Cipher.getOutputSize()` implementation to take into consideration the unprocessed input when returning the output size in AEAD ChaCha20 decryption.
Signed-off-by: Samer AL Masri <samasri@ibm.com>

Fixing failing OutputSizeTest

---

closed/make/launcher/Launcher-jdk.jcmd.gmk

Remove jdk.cmd man pages

---

closed/DDR.gmk

Depends on https://github.com/eclipse/openj9/pull/9380

Rename the com.ibm.jzos module to ibm.jzos

---

src/java.base/share/lib/security/default.policy

Required for https://github.com/eclipse/openj9/pull/9390

Add permissions to create system Thread for openj9.cuda & gpu

---

test/jdk/java/lang/ProcessBuilder/Basic.java

ProcessBuilder.Basic test expected MALLOCOPTIONS on AIX

---

closed/custom/Docs.gmk
closed/custom/Main.gmk

Create javadoc for only openj9 files

---

make/data/macosxsigning/default.plist
make/data/macosxsigning/java.plist
make/data/macosxsigning/jspawnhelper.plist

Issue: AdoptOpenJDK/openjdk-build#1778

Add OSX get-task-allow entitlement

---

make/data/macosxsigning/default.plist
make/data/macosxsigning/java.plist
make/data/macosxsigning/jspawnhelper.plist

Issue: AdoptOpenJDK/openjdk-build#1778

Revert: Add OSX get-task-allow entitlement

---

closed/custom/Images-pre.gmk

Include openj9.cuda and openj9.gpu in JRE

---

buildenv/jenkins/jobs/infrastructure/copyrightCheckDir.sh

https://github.ibm.com/runtimes/openjdk-contribution/issues/1247

JDK15 - GPLv2 is present but Classpath exception is missing

---

test/jdk/java/util/StringJoiner/MergeTest.java
test/jdk/java/util/StringJoiner/StringJoinerTest.java

Signed-off-by: Andrew Leonard <andrew_m_leonard@uk.ibm.com>

Add +CompactStrings to StringJoiner tests

---

closed/custom/common/Modules.gmk

Matches the preferred formatting used in the latest changes.

Fix formatting to use tabs not spaces

---

buildenv/jenkins/jobs/infrastructure/copyrightCheckDir.sh

Fixed jdk/test/java/awt/Frame/DecoratedExceptions/DecoratedExceptions.java

Copyright fix for JDk8

---

closed/autoconf/custom-hook.m4

Enable cmake by default on linux and mac platforms

---

closed/src/java.base/share/classes/com/sun/crypto/provider/NativeChaCha20Cipher.java

* issue eclipse/openj9#11689
Signed-off-by: Chao Shan <shanchao95@gmail.com>

Fix null nonce crash in ChaCha20Poly1305Param Test

---

closed/autoconf/custom-hook.m4

Enable cmake for Windows by default

---

closed/autoconf/custom-hook.m4

A replay of ibmruntimes/openj9-openjdk-jdk11#384 for jdknext.

Fix typo in comment

---

closed/autoconf/custom-hook.m4

Correct imbalance of `<` and `>` and use language consistent with other feedback in that option.

Fix help for '--with-openssl'

---

closed/src/java.base/share/classes/com/sun/crypto/provider/NativeChaCha20Cipher.java

This should resolve the discussion started here: https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/280#pullrequestreview-584651273.

Access nonce only when non-null

---

test/jdk/java/text/testlib/IntlTest.java

Issue https://github.com/eclipse/openj9/issues/12127

Update IntlTest to log uncaught exceptions

---

closed/DDR.gmk

Patch the DDR tools if present in the boot jdk

---

make/conf/jib-profiles.js
src/java.base/share/classes/sun/security/rsa/RSACore.java
src/java.desktop/aix/classes/sun/awt/X11InputMethod.java
src/java.desktop/macosx/classes/sun/lwawt/macosx/CDesktopPeer.java
src/java.desktop/macosx/classes/sun/lwawt/macosx/CTaskbarPeer.java
src/java.desktop/macosx/classes/sun/lwawt/macosx/CTrayIcon.java
src/java.desktop/share/classes/com/sun/media/sound/JavaSoundAudioClip.java
src/java.desktop/share/classes/java/awt/EventQueue.java
src/java.desktop/share/classes/java/awt/image/BandedSampleModel.java
src/java.desktop/share/classes/java/awt/image/ComponentSampleModel.java
src/java.desktop/share/classes/java/awt/image/Raster.java
src/java.desktop/share/classes/java/awt/image/SampleModel.java
src/java.desktop/share/classes/javax/print/attribute/standard/DialogOwner.java
src/java.desktop/share/classes/javax/swing/filechooser/FileSystemView.java
src/java.desktop/share/classes/sun/awt/image/PNGImageDecoder.java
src/java.desktop/share/classes/sun/font/lookup/JDKFontLookup.java
src/java.desktop/unix/classes/sun/java2d/x11/X11SurfaceData.java
src/java.desktop/windows/classes/sun/print/PrintServiceLookupProvider.java
src/jdk.jpackage/windows/native/common/MsiDb.h
test/hotspot/gtest/gc/shared/test_oopStorage.cpp
test/hotspot/jtreg/compiler/eliminateAutobox/TestEliminateBoxInDebugInfo.java
test/hotspot/jtreg/compiler/eliminateAutobox/TestIdentityWithEliminateBoxInDebugInfo.java
test/jdk/java/awt/image/Raster/CreateRasterExceptionTest.java
test/lib/jdk/test/lib/hexdump/ASN1Formatter.java
test/lib/jdk/test/lib/jfr/GCHelper.java
test/lib/jdk/test/lib/jfr/SimpleEventHelper.java

Merging master `HEAD` into `openj9-staging`
Resolved the conflict:
```
src/java.base/share/classes/sun/security/rsa/RSACore.java
```
Signed-off-by: Jason Feng fengj@ca.ibm.com

Merging master HEAD into openj9-staging - resolve conflict

---

closed/autoconf/version-numbers
closed/custom/Docs.gmk
closed/get_j9_source.sh
get_source.sh
src/java.base/share/classes/java/net/URLClassLoader.java
src/java.base/share/classes/jdk/internal/loader/BuiltinClassLoader.java

Issue bugzilla 541770
Signed-off-by: Adam Brousseau <adam.brousseau@ca.ibm.com>

Update eclipse org to eclipse-openj9

---

closed/make/modules/ibm.healthcenter/Copy.gmk

Stage healthcenter.properties to conf directory.
Signed-off-by: Joran Siu <joransiu@ca.ibm.com>

Stage healthcenter.properties to conf directory

---

src/java.base/share/classes/jdk/internal/loader/URLClassPath.java
src/java.base/unix/native/libjava/ProcessImpl_md.c
test/jdk/sun/misc/JarIndex/JarIndexMergeForClassLoaderTest.java
test/jdk/sun/misc/JarIndex/metaInfFilenames/Basic.java

Resolved conflicts:
```
src/java.base/share/classes/jdk/internal/loader/URLClassPath.java
```

Merge master HEAD into openj9-staging

---

closed/AsyncGetCallTrace.gmk
closed/OpenJ9.gmk
closed/custom/Main.gmk

Issue: eclipse-openj9/openj9#12276.

Build AsyncGetCallTraceTest shared library on Linux

---

closed/src/java.base/share/classes/com/sun/crypto/provider/NativeChaCha20Cipher.java

Signed-off-by: alonsh <alonsh@ca.ibm.com>

Fix ChaCha20 context release code to use cleaner

---

closed/make/modules/jdk.jcmd/Launcher.gmk

Issue https://github.com/eclipse-openj9/openj9/issues/13804

Remove inappropriate jmap man page

---

closed/src/java.base/share/classes/com/sun/crypto/provider/NativeCipherBlockChaining.java
closed/src/java.base/share/classes/com/sun/crypto/provider/NativeGaloisCounterMode.java

Porting PR [openj9-openjdk-jdk17#51](https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/51)
Signed-off-by: Zainab Fatmi <zainab@ibm.com>

Fix crash in native crypto on concurrent cipher object use with GCM

---

test/jdk/java/lang/reflect/MethodHandleAccessorsTest.java

Related: https://github.com/eclipse-openj9/openj9/issues/14084

Remove exception message check

---

closed/src/java.base/aix/native/libjncrypto/NativeCrypto_md.c
closed/src/java.base/macosx/native/libjncrypto/NativeCrypto_md.c
closed/src/java.base/share/classes/jdk/crypto/jniprovider/NativeCrypto.java
closed/src/java.base/share/native/libjncrypto/NativeCrypto.c
closed/src/java.base/share/native/libjncrypto/NativeCrypto_md.h
closed/src/java.base/unix/native/libjncrypto/NativeCrypto_md.c
closed/src/java.base/windows/native/libjncrypto/NativeCrypto_md.c
test/jdk/com/sun/crypto/provider/Cipher/AEAD/GCMParameterSpecTest.java

Signed-off-by: Jinhang Zhang <Jinhang.Zhang@ibm.com>

Add openssl version 3.0+ support for Linux platforms

---

src/java.base/share/classes/java/lang/Thread.java

* Consolidate private constructors;
* Replace `cleanup()` w/ `exit()`;
* Removed `tidCount`/`createCount`/`deadInterrupt`.
depends on https://github.com/eclipse-openj9/openj9/pull/14960

Adopt RI java.lang.Thread

---

closed/src/java.base/share/classes/java/io/ClassByNameCache.java
src/java.base/share/classes/java/io/ObjectInputStream.java

See https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/388
https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/99

Rename CacheNameClass to ClassByNameCache

---

src/java.base/share/classes/sun/security/provider/SunEntries.java

add import sun.security.action.GetPropertyAction

Fix SunEntries dependency

---

src/java.base/share/classes/java/lang/Thread.java

Fix Thread.stop if-condition typo

---

closed/custom/modules/java.base/Copy.gmk
closed/src/java.base/share/classes/openj9/internal/security/FIPSConfigurator.java
closed/src/java.base/share/conf/security/nss.fips.cfg
src/java.base/share/classes/java/security/SecureRandom.java
src/java.base/share/classes/java/security/Security.java
src/java.base/share/classes/module-info.java
src/java.base/share/classes/sun/security/provider/SunEntries.java
src/java.base/share/lib/security/default.policy
src/jdk.crypto.ec/share/classes/sun/security/ec/SunEC.java
test/jdk/ProblemList-fips.txt

Resolved conflicts:
```
src/java.base/share/classes/java/security/SecureRandom.java
```

Merge latest openj9 into openj9-staging

---

src/java.base/share/classes/java/lang/Thread.java

Depends on: https://github.com/eclipse-openj9/openj9/pull/15330

add Thread.registerNatives

---

src/java.base/share/classes/java/lang/Thread.java

Remove unnecessary interrupt call
Signed-off-by: Tobi Ajila <atobia@ca.ibm.com>

Remove unnecessary interrupt call

---

src/java.base/share/classes/jdk/internal/foreign/abi/ppc64/aix/AixPPC64VaList.java
src/java.base/share/classes/jdk/internal/foreign/abi/ppc64/sysv/SysVPPC64leVaList.java

[VaList/Power]Replace with Math.min() in getSmallerStructArgSize

---

buildenv/jenkins/jobs/infrastructure/copyrightCheckDir.groovy

Signed-off-by: Adam Brousseau <adam.brousseau@ca.ibm.com>

Add Reference repo to git clone

---

buildenv/jenkins/jobs/infrastructure/copyrightCheckDir.sh

The files are resolved by
https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/635

Remove fixed CPE exceptions from copyrightCheckDir.sh

---

src/java.base/share/classes/java/lang/VirtualThread.java

mutual dependency: https://github.com/eclipse-openj9/openj9/pull/16855

Initialize Continuation.vthread in constructor

---

src/java.base/share/classes/jdk/internal/foreign/CABI.java

Fix the compilation issue with the OS property in CABI.java

---

closed/get_openssl_source.sh

PRs for other versions
https://github.com/ibmruntimes/openj9-openjdk-jdk20/pull/37
https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/89
https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/198
https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/640
https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/656

Allow any text without whitespace for the openssl version

---

closed/src/java.base/macosx/native/libjncrypto/NativeCrypto_md.c
closed/src/java.base/windows/native/libjncrypto/NativeCrypto_md.c

Allow loading of OpenSSL 3.x native library for Mac and Windows platforms

---

closed/test/jtreg-ext/requires/OpenJ9PropsExt.java

Issue https://github.com/eclipse-openj9/openj9/issues/17631

Add cds.write.archived.java.heap, ZGenerational to OpenJ9PropsExt

---

src/java.base/share/classes/java/lang/Thread.java

Related:
- https://github.com/eclipse-openj9/openj9/pull/17402
- https://github.com/eclipse-openj9/openj9/issues/16677

Set scoped value bindings for newly-created thread

---

closed/test/jtreg-ext/requires/OpenJ9PropsExt.java

Related: https://github.com/eclipse-openj9/openj9/issues/18038

Set vm.opt.final.ClassUnloading to true

---

make/conf/version-numbers.conf

Fixes https://github.com/eclipse-openj9/openj9/issues/18211.

Allow JDK 20 for boot jdk

---

make/autoconf/jvm-features.m4

Avoid problem seen in https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/681#issuecomment-1777312700.

Disable JVMCI feature for OpenJ9

---

src/java.base/share/classes/java/lang/Thread.java

Related to: https://github.com/eclipse-openj9/openj9/issues/16659

Clear vmthread from thread object at shutdown

---

src/java.base/share/classes/java/net/URLClassLoader.java
src/java.base/share/classes/jdk/internal/loader/URLClassPath.java

Eliminate unnecessary differences as compared with upstream and:
* make classes and fields final as appropriate
* don't use raw types
* remove redundant initializers
* remove unused parameter/overload
* remove unused imports
* fix compile warnings
* correct indentation
* finish sentences with periods
This opportunity was noticed while reviewing #674.

Improve patches to URLClassLoader and URLClassPath

---

test/jdk/java/lang/Thread/virtual/stress/Skynet.java

Related: https://github.com/eclipse-openj9/openj9/issues/16728

Update stack increment option in Skynet test

---

closed/OpenJ9.gmk

Required by https://github.com/eclipse-openj9/openj9/pull/18571.

Include new "access" shared library in test-image

---

make/conf/version-numbers.conf
src/jdk.compiler/share/classes/com/sun/tools/javac/comp/TransLiterals.java
src/jdk.javadoc/share/classes/jdk/javadoc/internal/tool/Start.java

This reverts #671, #696 and #719.

Revert allowances for using a Java 20 boot JDK

---

closed/custom/modules/java.base/Copy.gmk

Remove z/OS from platforms copying static jvm/jsig libaries into image

Remove z/OS from platforms copying static jvm/jsig libaries into image

---

src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/P11TlsMasterSecretGenerator.java
src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/SunPKCS11.java
src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/wrapper/CK_MECHANISM.java
src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/wrapper/CK_NSS_TLS_EXTENDED_MASTER_KEY_DERIVE_PARAMS.java
src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/wrapper/Functions.java
src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/wrapper/PKCS11Constants.java
src/jdk.crypto.cryptoki/share/native/libj2pkcs11/p11_convert.c
src/jdk.crypto.cryptoki/share/native/libj2pkcs11/p11_keymgmt.c
src/jdk.crypto.cryptoki/share/native/libj2pkcs11/p11_util.c
src/jdk.crypto.cryptoki/share/native/libj2pkcs11/pkcs11t.h
src/jdk.crypto.cryptoki/share/native/libj2pkcs11/pkcs11wrapper.h

This PR is for adding the ExtendedMasterSecret support in SunPKCS11 security provider.

Add EMS support in SunPKCS11 provider

---

make/conf/version-numbers.conf

Fixes https://github.com/eclipse-openj9/openj9/issues/19269.

Allow JDK 21 for boot jdk

---

test/jdk/java/foreign/StdLibTest.java

If native encoding charset is not one of the standard charset, allocate
segment using native encoded bytes for the string for printf down call
in StdLibTest.

Fix StdLibTest for platforms with non standard native charset

---

test/jdk/ProblemList-OpenJCEPlusFIPS.FIPS140-3-Test-TLS-JKS.txt
test/jdk/ProblemList-OpenJCEPlusFIPS.FIPS140-3-Test-TLS-PKCS12.txt

Add FIPS problem list placeholder
Issue: backlog/issues/1529

Add FIPS problem list placeholder

---

make/Main.gmk

Issue: https://github.com/eclipse-openj9/openj9/issues/20746.

Don't try to build static-jdk-image

---

test/jdk/java/foreign/largestub/TestLargeStub.java

Related: https://github.com/eclipse-openj9/openj9/issues/20355

Reduce available slots to match the upper limit supported by OpenJ9

---

closed/autoconf/custom-spec.gmk.in

Related to https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/928

Remove obsolete FREEMARKER_JAR make variable

---

closed/src/java.base/share/classes/java/io/ClassByNameCache.java
closed/src/java.base/share/classes/jdk/crypto/jniprovider/NativeCrypto.java
closed/src/java.base/share/classes/openj9/internal/security/RestrictedSecurity.java

Related to https://github.com/eclipse-openj9/openj9/issues/20563
Port to 24 https://github.com/ibmruntimes/openj9-openjdk-jdk24/pull/19

Remove AccessController.doPrivileged uses from closed/src

---

closed/custom/modules/java.base/Copy-post.gmk

Issue https://github.ibm.com/runtimes/semeru-runtimes/issues/10

Copy the verbose gc schema.xsd into the build

---

buildenv/jenkins/jobs/infrastructure/copyrightCheckDir.sh

* fix typos
* correct indentation
* add missing punctuation

Tidy up copyright check script

---

test/hotspot/jtreg/serviceability/jvmti/vthread/StopThreadTest/StopThreadTest.java
test/jdk/java/lang/Thread/virtual/LockingMode.java

Forward port of
https://github.com/ibmruntimes/openj9-openjdk-jdk24/pull/14
https://github.com/ibmruntimes/openj9-openjdk-jdk24/pull/31
For https://github.com/eclipse-openj9/openj9/issues/20706

Set tests legacy locking to true

---

test/jdk/ProblemList-OpenJCEPlus.txt

related: https://github.com/adoptium/aqa-tests/pull/6129 and automation/issues/78

Add ProblemList-OpenJCEPlus.txt as placeholder

---

make/conf/version-numbers.conf

This reverts commit 7eecd87f883765a779e8221e998ec25a4183605c.

Revert "Allow JDK 21 for boot jdk"

---

src/java.base/share/classes/java/io/ObjectInputStream.java
src/java.base/share/classes/jdk/internal/javac/PreviewFeature.java
src/jdk.compiler/share/classes/com/sun/tools/javac/comp/Check.java
src/jdk.javadoc/share/classes/jdk/javadoc/internal/doclets/formats/html/ModuleWriter.java

Issues
https://github.com/eclipse-openj9/openj9/issues/19694
https://github.com/eclipse-openj9/openj9/issues/19994
https://github.com/eclipse-openj9/openj9/issues/20402
Reverting
https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/827
https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/866
part of https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/892
https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/909/

Remove temporary changes supporting bootjdk 21

---

src/java.base/share/classes/java/lang/Thread.java

It is possible for the Java and native interrupt status to get out of
sync. Sending two interrupts to the same thread in quick succession can
cause this. It is critical that clearing the interrupt status also
clears the native status. If the Java interrupt status is false, it is
important to verify that this is consistent with the native status to
prevent an unexpected interrupt exception the next time sleep() or
wait() is called.
Related to https://github.com/eclipse-openj9/openj9/issues/21804

Fix thread interrupt status

---

closed/test/jtreg-ext/requires/OpenJ9PropsExt.java

Issue https://github.com/eclipse-openj9/openj9/issues/21733
See https://github.com/ibmruntimes/openj9-openjdk-jdk25/pull/11 for testing.

Set java.enablePreview and jdk.static openjdk test properties

---

closed/src/java.base/share/classes/sun/security/ec/NativeXDHKeyPairGenerator.java

This reverts https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/1077.

Revert "Add thread safety for generateKeyPair in NativeXDHKeyPairGenerator"
