closed/OpenJ9.gmk, closed/make/Main.gmk, closed/make/common/JdkNativeCompilation.gmk
The way 'closed' source overrides are selected has changed recently in openjdk. To adapt, we need to hook into JdkNativeCompilation.gmk.
The 'jre-image' target has been removed in favour of 'legacy-jre-image'. The targets that depended upon jre-image were not normally used nor needed: they have been removed.
Populating $(JDK_OUTPUTDIR) is required even if given a 'build jdk'.
=> Fix build errors with latest openjdk11

closed/OpenJ9.gmk
Some files must be copied both to the build JDK and to module_libs/java.base (for inclusion in java.base.jmod).
=> Ensure files will be included in java.base.jmod

closed/autoconf/custom-spec.gmk.in
Export the autoconf cache variables for CC/CXX. This determines the program
autoconf runs its tests on, without clobbering the CC/CXX variables.
Also remove the CONFIG_SHELL variable export as it is not required, and
does not solve the underlying issue
=> Fix omr configure issues with ccache

closed/OpenJ9.gmk, make/common/SetupJavaCompilers.gmk
Bringup `JDK12`
Backport release `10` compilation to workaround `nestmates` issue;
Adopt `JDK12 redirector` library.
Along with https://github.com/eclipse/openj9/pull/2458, this PR produces following `-version` output:
```
openjdk version "12-internal" 2019-03-19
OpenJDK Runtime Environment (build 12-internal+0-adhoc.jason.openj9-openjdk-jdk)
Eclipse OpenJ9 VM (build jvminitarch-64099b4, JRE 12 Linux amd64-64-Bit Compressed References 20180723_000000 (JIT enabled, AOT enabled)
OpenJ9   - 64099b4
OMR      - 9bf4244
JCL      - b16ce2c based on jdk-11+19)
```
FYI: @andrew-m-leonard @DanHeidinga 
=> Bringup JDK12

closed/OpenJ9.gmk
Move the run ddrgen step outside of the building VM step in order to
resolve DDR dependencies better.
This PR moves the run ddrgen step to after the VM is built, and needs to be delivered together with https://github.com/eclipse/openj9/pull/2588.
Signed-off-by: mikezhang <mike.h.zhang@ibm.com>
=> Move ddrgen step after building vm

src/java.base/share/native/libjimage/NativeImageBuffer.cpp, src/java.base/unix/native/include/jni_md.h
Define `JNIEXPORT` and `JNIIMPORT` for xlc version 13.1 or newer. Without this, almost no symbols are exported from shared libraries due to use of `-qvisibility=hidden` as specified in `make/lib/LibCommon.gmk`. The symptoms are reported in eclipse/openj9#2468.
Unfortunately, this encounters a bug in xlc: it fails to parse what seems to be reasonable code. A workaround is required in just one place: `src/java.base/share/native/libjimage/NativeImageBuffer.cpp`.
This is a replay of https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/15.
=> Enable AIX build with xlc 13.1

closed/OpenJ9.gmk, closed/make/Main.gmk, closed/make/copy/Copy-java.base.gmk
* explicitly associate content with modules
* collect available libraries for test-image
* ensure directory exists for jvm.cfg
=> Rework creation of images and build JDK

make/common/SetupJavaCompilers.gmk
Reverts #12. Similarly to https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/21
=> Reverts #12, javac compile with source 11 target 11

make/common/SetupJavaCompilers.gmk
Subsequent to #12, openjdk changed to use source 12 target 12. Thanks
@keithc-ca for noticing. Corrects #33
=> javac compile with source 12 target 12

src/java.base/share/classes/jdk/internal/loader/BuiltinClassLoader.java
Add `doPrivileged` for security sensitive calls
Otherwise following security exception might be thrown in certain testcase.
```
Caused by: java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "accessSystemModules")
at java.base/java.security.AccessController.throwACE(AccessController.java:176)
at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:237)
at java.base/java.security.AccessController.checkPermission(AccessController.java:373)
at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
at java.base/jdk.internal.module.SystemModuleFinders$SystemModuleReader.checkPermissionToConnect(SystemModuleFinders.java:406)
at java.base/jdk.internal.module.SystemModuleFinders$SystemModuleReader.<init>(SystemMo …
```
=> Add doPrivileged for security sensitive calls

closed/autoconf/custom-hook.m4
Signed-off-by: mikezhang <mike.h.zhang@ibm.com>
=> Enable DDR by default on AIX

closed/autoconf/custom-hook.m4
Reverts ibmruntimes/openj9-openjdk-jdk#35
as per eclipse/openj9#3248
=> Revert "Enable DDR by default on AIX"

src/java.base/share/classes/java/net/URLClassLoader.java
Handle IllegalArgumentException when parallel classloaders define the same
package. cf. eclipse/openj9#3038
=> Handle race condition in shared classes defineClass()

closed/OpenJ9.gmk, closed/autoconf/custom-hook.m4, closed/autoconf/custom-spec.gmk.in
* `--with-openj9-cc`  : select C compiler
* `--with-openj9-cxx` : select C++ compiler
* `--with-openj9-developer-dir` : select Xcode version (MacOS)
This is a replay of https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/147.
=> Allow configuring distinct compilers for OpenJ9

closed/OpenJ9.gmk, make/lib/Lib-java.base.gmk
Use the OpenJ9 implementation of libjsig.so and don't include a copy in the compressedrefs/default directory.
This is a replay of https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/52 and https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/58 for Java 12.
=> Use OpenJ9 implementation of libjsig.so

src/java.base/share/native/libjimage/NativeImageBuffer.cpp, src/java.base/unix/native/include/jni_md.h
When you are building OpenJDK on AIX with a version of the xlC
compiler that is not 12.1, OpenJDK adds the qvisibility option
to the xlC_r command line.
This breaks things, and prevents the build from completing.
To compensate, we added some changes into extensions.
The community has been contacted about the bug, and elected to break
the problem into 2 stages.
1. Remove the qvisibility option to enable the builds to pass in the
short term.
2. Add the qvisibility option back in, and add whatever code is
needed to allow builds and testing to complete successfully.
Since step 1 is complete, we don't need our work-around code anymore.
This commit removes that workaround code.
Signed-off-by: Adam Farley <adam.farley@uk.ibm.com>
=> AIX xlC qvisibility extension removal

src/java.base/share/classes/java/net/URLClassLoader.java
Shared classes should call getAndVerifyPackage() instead of deprecated
getPackage()
Fixes: eclipse/openj9#4113
Signed-off-by: hangshao <hangshao@ca.ibm.com>
=> Call getAndVerifyPackage() in shared classes patch

src/java.base/share/lib/security/default.policy
<details><summary>Initial PR description (for background info)</summary>
<p>
Add `openj9.gpu` to boot module list
This allows module `openj9.gpu` to access `java.base/com.ibm.gpu.spi.GPUAssist.Provider`.
closes: https://github.com/eclipse/openj9/issues/3213
`java.base/java.util.GPUAssistHolder` attempts to load `openj9.gpu/com.ibm.gpu.internal.CudaGPUAssistProvider` as per following stacktrace:
```
at java.base/java.util.ServiceLoader.loadProvider(ServiceLoader.java:862)
at java.base/java.util.ServiceLoader$ModuleServicesLookupIterator.hasNext(ServiceLoader.java:1076)
at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
at java.base/java.util.GPUAssistHolder.gpuAssist(GPUAssistHolder.java:33)
at …
```
=> Add permissions required by module openj9.gpu & openj9.cuda

closed/OpenJ9.gmk
* on Windows the shared library should be in `bin`, `bin/j9vm` and `bin/server` (in an SDK, the static library should be in `lib`)
* on other platforms, the shared library should be in `lib`, `lib/j9vm` and `lib/server`
* also put the redirector static library where openjdk expects it
This is a replay of ibmruntimes/openj9-openjdk-jdk11#97 for Java 13.
=> Put jsig libraries in the correct places

src/java.base/share/classes/jdk/internal/loader/BuiltinClassLoader.java
Remove `Lambda expression` to avoid bootstrap problem
When `jdk.internal.lambda.dumpProxyClasses` is enabled, this triggers `Module` method calls before `java.base` is created, and caused `null` module object is returned and eventually `NPE`.
Replaced `Lambda` expression with `anonymous` class avoid such bootstrap problem.
Related to https://github.com/eclipse/openj9/issues/3399
FYI: @DanHeidinga @hangshao0 
=> Remove Lambda expression to avoid bootstrap problem

closed/autoconf/custom-hook.m4
A replay of https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/115 for Java 13.
=> Chose the latest applicable OPENJDK_TAG

src/java.base/share/classes/java/net/URLClassLoader.java, src/java.base/share/classes/jdk/internal/loader/BuiltinClassLoader.java, src/java.base/share/classes/jdk/internal/loader/Resource.java, src/java.base/share/classes/jdk/internal/loader/URLClassPath.java, src/java.base/share/classes/jdk/internal/module/ModuleBootstrap.java, src/java.rmi/share/classes/sun/rmi/server/LoaderHandler.java
Replace `IBM-shared_classes_misc` with `OpenJ9-shared_classes_misc`
Update shared classes specific comments.
ibmruntimes/openj9-openjdk-jdk11#114 for jdk
=> Replace IBM-shared_classes_misc with OpenJ9-shared_classes_misc

src/java.base/share/classes/sun/nio/cs/US_ASCII.java
Replace `IBM-perf_converter` with `OpenJ9-perf_converter`
Update perf converter specific comments.
=> Replace IBM-perf_converter with OpenJ9-perf_converter

closed/OpenJ9.gmk
Depends on and required by https://github.com/eclipse/openj9/pull/4647.
=> Use the singular jvm shared library

closed/make/Main.gmk
A replay of https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/134 for Java 13.
=> Only run 'java -version' if not cross compiling

closed/autoconf/version-numbers, make/autoconf/jdk-version.m4
Supply `OpenJ9 VENDOR` info in a file `version-numbers`
`OpenJ9` specific `VENDOR` info `COMPANY_NAME`, `VENDOR_URL` and `VENDOR_URL_BUG` are supplied within `closed/autoconf/version-numbers`;
`jdk-version.m4` processes the variables from this new file `version-numbers` besides `autoconf/version-numbers`. These `VENDOR` info becomes part of `java.lang.VersionProps.java` and eventually are set to system property values for `java.vendor`, `java.vendor.url` and `java.vendor.url.bug`.
Manually verified this fix the system property `java.vendor` value in #4660.
FYI: @DanHeidinga 
=> Supply OpenJ9 VENDOR info in a file version-numbers

closed/OpenJ9.gmk
Use `pConfig JAVA13` at head extension
Changed `JAVA12` to `JAVA13`.
Manually verified that `JDK13` can be built and `-version` output is:
```
openjdk version "13-internal" 2019-09-17
OpenJDK Runtime Environment (build 13-internal+0-adhoc.jason.openj9-openjdk-jdk)
Eclipse OpenJ9 VM (build master-9d606fc, JRE 13 Linux amd64-64-Bit Compressed References 20190225_000000 (JIT enabled, AOT enabled)
OpenJ9   - 9d606fc
OMR      - e6c6285
JCL      - b0f7ca0 based on jdk-13+6)
```
Related: https://github.com/eclipse/openj9/issues/4857, https://github.com/eclipse/openj9/pull/4877
Reviewer: @DanHeidinga
FYI: @andrew-m-leonard 
=> Use pConfig JAVA13 at head extension

src/java.desktop/share/native/libawt/awt/image/gif/gifdecoder.c
=> Correct GifImageDecoder.parseImage JNI interlace param type

buildenv/jenkins/jobs/infrastructure/copyrightCheckDir.sh
Test run in https://ci.eclipse.org/openj9/view/Sandbox/job/CopyrightCheck-OpenJDK11-Simon/90/console
=> Exclude FieldGen.sh from in-jdk copyright checks

closed/autoconf/custom-hook.m4
Don't consider tags attached to descendant commits.
See ibmruntimes/openj9-openjdk-jdk11#142.
=> Improve git tag resolution

closed/autoconf/custom-hook.m4
Use only options that are available on all platforms.
See: https://github.com/eclipse/openj9/issues/4932
=> Remove use of 'sort -V'

closed/src/jdk.internal.vm.ci/share/classes/module-info.java
Tabs are not supported by the dependency discovery mechanism in openjdk.
See also eclipse/openj9#5260.
=> Use spaces instead of tabs in module-info files

closed/make/Main.gmk, closed/make/copy/Copy-java.base.gmk
Generating jvmti.h before initialization of macros in Main.mk.
There are some additional information:
- The related issue is https://github.com/eclipse/openj9/issues/2368
- Add dependency in Main.mk to support the generation of jvmti.h before it starts to build openj9
Signed-off-by: MarkQingGuo <Qing.Guo@ibm.com>
=> Add dependency in Main.mk to support the generation of jvmti.h

closed/make/CompileJavaModules.gmk, closed/make/closed_make/launcher/Launcher-jdk.jcmd.gmk
Update jps and jstack packages to match OpenJ9
Requires https://github.com/eclipse/openj9/pull/5150
=> Add launcher for jstack

closed/make/Main.gmk
A replay of ibmruntimes/openj9-openjdk-jdk8#281 for Java 13.
=> Use 'tee' for visibility of 'java -version' failures

closed/src/java.base/share/classes/com/sun/crypto/provider/NativeCipherBlockChaining.java, closed/src/java.base/share/classes/com/sun/crypto/provider/NativeGaloisCounterMode.java
Same as https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/152
=> Add a check for illegal key size for native AES-CBC and AES-GCM

closed/autoconf/custom-hook.m4
OpenJ9 JIT requires NASM version 2.13+ on x86 platform.
Issue: eclipse/openj9#4653
Signed-off-by: Nazim Uddin Bhuiyan <Nazim.Uddin.Bhuiyan@ibm.com>
=> Verify the minimum NASM version requirement is met on x86-64

closed/src/java.base/share/classes/java/io/ClassCache.java
Create thread in `SystemThreadGroup` and not inherit `ThreadLocals`
Created the thread via `com.ibm.oti.vm.VM.getVMLangAccess().createThread()`.
This thread is expected to be alive along with `JVM` hence belongs to the system thread group.
This thread doesn't need inherit `ThreadLocals` and avoid copying `ThreadLocals` which causes `NPE` in some use scenarios.
Note: this is the replay of https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/170.
=> Create thread in SystemThreadGroup and not inherit ThreadLocals

src/java.desktop/share/native/libawt/awt/image/gif/gifdecoder.c
We removed out only extensions patch to this file, but did not
remove the ibm copyright notice afterwards.
Signed-off-by: Adam Farley <adam.farley@uk.ibm.com>
=> Remove unneeded ibm copyright

buildenv/jenkins/jobs/infrastructure/copyrightCheckDir.sh
Test runs:
closed/* only, trace on: https://ci.eclipse.org/openj9/view/Sandbox/job/CopyrightCheck-OpenJDK11-Simon/92/
all files, trace off: https://ci.eclipse.org/openj9/view/Sandbox/job/CopyrightCheck-OpenJDK11-Simon/93/
=> Exclude openjdk tag file from copyright check

src/jdk.jdwp.agent/share/native/libjdwp/export/sys.h, src/jdk.jdwp.agent/unix/native/libjdwp/linker_md.c, src/jdk.jdwp.agent/windows/native/libjdwp/linker_md.c
Currently, if the cumulative total length of all possible library
paths is greater than the maximum length of a single path (on this
OS), then the path to the library is left blank. This results in
failure to load the library.
This fix is the all-platforms port for the PR linked below, and
enables each separate path to be measured for length independent of
its neighbours.
https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/107
Signed-off-by: Adam Farley <adam.farley@uk.ibm.com>
=> Allow multiple possible library paths

src/java.base/share/lib/security/default.policy
Added following permissions:
```
permission java.lang.RuntimePermission "accessClassInPackage.com.ibm.oti.util";
permission java.lang.RuntimePermission "accessClassInPackage.com.ibm.tools.attach.target";
permission java.lang.RuntimePermission "accessClassInPackage.openj9.tools.attach.diagnostics.base";
permission java.util.PropertyPermission "com.ibm.tools.attach.*", "read";
permission java.io.FilePermission "<<ALL FILES>>", "read,write,delete";
permission java.net.SocketPermission "localhost:1024-", "accept,resolve";
```
Note: ported from https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/193
Related: https://github.com/eclipse/openj9/pull/6263
=> Add permissions required by module jdk.attach

closed/OpenJ9.gmk, closed/make/DDR.gmk, closed/make/Main.gmk
* put j9ddr.dat in the correct directory on Windows
* build j9ddr.jar a prerequisite of openj9.dtfj-launchers
See eclipse/openj9#6998.
=> Include DDR support in the 'exploded-image'

buildenv/jenkins/jobs/infrastructure/copyrightCheckDir.sh
Fixing */share/classes/sun/security/util/math/intpoly/FieldGen.jsh path the correct path for all java versions
=> Fixing */share/classes/sun/security/util/math/intpoly/FieldGen.jsh path

buildenv/jenkins/jobs/infrastructure/copyrightCheckDir.sh
Fixing Path for copyrights for version jdk8
echo "closed/adds/jdk/src/windows/native/jdk/crypto/jniprovider/NativeCrypto_md.c"
>>$TEMPFILE
=> Fixing Path for copyrights for version jdk8

test/hotspot/jtreg/TEST.ROOT
Some hotspot tests apply to Openj9, which we'd like to run them regularly in test builds or run manually. In that case unset Hotspot VMProps ProdDefns requires class and replace with optional OpenJ9 class is necessary.
Signed-off-by: Sophia Guo sophiag@ca.ibm.com
=> Set OpenJ9 ProdDefns requires class

src/java.base/share/classes/jdk/internal/module/jdk8_packages.dat, src/java.base/share/lib/security/default.policy
**Rename com.ibm.tools.attach.target to openj9.internal.tools.attach.target**
Updated the references accordingly.
Depends: eclipse/openj9#7279
Reviewer: @pshipton
FYI: @DanHeidinga
=> Rename com.ibm.tools.attach.target to openj9.internal.tools.attach.target

src/java.base/share/classes/java/io/ObjectInputStream.java
An Issue has been found with LUDCL in OpenJ9. The wrong class loader is cached causing a ClassNotFoundException. Disabling this feature by default until this is resolved. https://github.com/eclipse/openj9/issues/7332
Signed-off-by: Theresa Mammarella <Theresa.T.Mammarella@ibm.com>
=> Disable LUDCL by default

closed/autoconf/custom-hook.m4
* properly handle paths with spaces like
`C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0`
=> Fix paths for CUDA_HOME and GDK_HOME on Windows

make/common/Modules.gmk
Fixes: https://github.com/eclipse/openj9/issues/7248
FYI @andrew-m-leonard 
Signed-off-by: Adam Thorpe <adam.thorpe@ibm.com>
=> Removed /r (CR) characters from module names in Modules.gmk

src/jdk.jdwp.agent/share/native/libjdwp/export/sys.h
Fixes a problem when an openj9 patch was added to openjdk, but this file was not updated when the openjdk code was merged.
Fixes https://github.com/ibmruntimes/openj9-openjdk-jdk/issues/146
FYI @pshipton
Signed-off-by: Adam-Thorpe <adam.thorpe@ibm.com>
=> Corrected declaration of linker_md.c method to match openjdk

make/autoconf/flags-ldflags.m4
Otherwise the JIT codecache can't be set executable.
Issue https://github.com/eclipse/openj9/issues/5074
=> Remove -bnorwexec link option on AIX

src/java.base/share/classes/java/io/ObjectInputStream.java
Port from ibmruntimes/openj9-openjdk-jdk8#341
Doc issue: eclipse/openj9-docs#413
The assumption that the ludcl will not change during a call to readObject/readUnshared can only be made if user code is not invoked. This change triggers a refresh of the cachedLudcl when a user method is invoked.
Re-enable ludcl caching by default (com.ibm.enableClassCaching)
Signed-off-by: Theresa Mammarella Theresa.T.Mammarella@ibm.com
=> Fix LUDCL optimization

make/launcher/LauncherCommon.gmk
Sets the load address of the launchers to 0x60000 on zlinux 64 systems. This enables compressed references with shift 0 for big heap sizes
**Before:**
```
80000000-80001000 r-xp 00000000 fd:01 12720136                           /java
80002000-80003000 r--p 00001000 fd:01 12720136                           /java
80003000-80004000 rw-p 00002000 fd:01 12720136                         /java
```
**After:**
```
00060000-00062000 r-xp 00000000 fd:01 12596074                          /java
00062000-00063000 r--p 00001000 fd:01 12596074                           /java
00063000-00064000 rw-p 00002000 fd:01 12596074                         /java
```
Issue: https://github.com/eclipse/openj9/issues/7115
Signed-off-by: Morgan Davies <morgan.davies@ibm.com>
=> Set default load address for launchers on s390x

make/launcher/LauncherCommon.gmk
Set the load address for 64 bit aix to 0x100,0000,0000 (1TB) for launchers. This ensures that the text/data segment is out of the way of compressed heap allocation.
**Before:**
```
100000000         100016332              88K r-x   m     MAINTEXT   8c0b18           java 
110000b84         110009940              35K rw-   m     MAINDATA   80b1c1           java
```
**After:**
```
10000000000       10000025a32           150K r-x   m     MAINTEXT   8a1594           java 
10010000dd0       10010009ce0            35K rw-   m     MAINDATA   82a0a5           java 
```
Issue: https://github.com/eclipse/openj9/issues/7458
Signed-off-by: Morgan Davies <morgan.davies@ibm.com>
=> Set base text/data load address on aix

closed/make/Docs.gmk, closed/make/common/Modules.gmk
This PR is the equivalent of https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/212 for the openj9-openjdk-jdk (jdk head) repository.
=> Fix openj9 javadoc

closed/autoconf/custom-hook.m4
With the change in eclipse/openj9#8145, `OpenSSL` symbols are
dynamically loaded at the runtime. During the build time,
there is no longer a dependency on the installed `OpenSSL`
version on the build machines. Removed the code that
checks `SSL_CTX_set_ecdh_auto` during config.
Signed-off-by: Annabelle Huo <Annabelle.Huo@ibm.com>
=> Remove the check on a specific OpenSSL API for JITServer

buildenv/jenkins/jobs/infrastructure/copyrightCheckDir.sh
This copyright has mentioned about sample files which are not even part of
OpenJDK file structure hence excluding.
=> src/solaris/native/sun/security/smartcardio/MUSCLE/COPYING copyrights issue in JDK 8

closed/OpenJ9.gmk, closed/make/Main.gmk, closed/make/common/Modules.gmk
This is a replay of ibmruntimes/openj9-openjdk-jdk11#256 for Java next.
=> Improve integration of OpenJ9 JCL code generation

closed/autoconf/custom-hook.m4
* `BASIC_FIXUP_PATH` -> `UTIL_FIXUP_PATH`
* `BASIC_REQUIRE_PROGS` -> `UTIL_REQUIRE_PROGS`
Fixes https://github.com/eclipse/openj9/issues/8634
=> Adjust for refactoring of configure functions

make/autoconf/jdk-options.m4, make/common/NativeCompilation.gmk
* support all choices for '--with-native-debug-symbols'
See eclipse/openj9#8821.
=> AIX: create .debuginfo files

src/java.base/unix/native/libjli/java_md_solinux.c
The previous setting `MALLOCOPTIONS=multiheap,buckets` caused
Issue eclipse/openj9#8842
=> Set environment variable MALLOCOPTIONS=multiheap on AIX

closed/src/java.base/share/native/libjncrypto/NativeCrypto.c
Openssl 1.0.2 is not safely used in multi-thread application.
The change adds threadid and locking callback functions to provide
thread-safety when openssl 1.0.2 is used. It fixes issue 8373,
test crash in openjdk, jdk_net_0,
com/sun/net/httpserver/Test9a.java
Signed-off-by: Chao Shan <chao.shan@ibm.com>
=> Add openssl thread synchronization to fix crashes

src/java.base/unix/native/libjli/java_md_solinux.c
The previous setting `MALLOCOPTIONS=multiheap` uses too much memory in
some cases.
Issue eclipse/openj9#8842
=> Set env var MALLOCOPTIONS=multiheap,considersize on AIX

closed/src/java.base/share/native/libjncrypto/NativeCrypto.c
As suggested in https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/381#discussion_r404423466.
=> Use CloseHandle() to destroy a mutex on Windows

closed/DDR.gmk
This is a replay of ibmruntimes/openj9-openjdk-jdk11#291 for Java next.
=> Fix J9DDR compile commands

test/jdk/java/lang/ProcessBuilder/Basic.java
See https://github.com/AdoptOpenJDK/openjdk-tests/pull/1699
Setting the options via the test harness, either on the command line or
in the environment via OPENJ9_JAVA_OPTIONS, doesn't affect the
sub-process.
By the time a JTReg test is running, the environment has been purged.
i.e.
```
{PATH=/bin:/usr/bin:/usr/sbin, DISPLAY=:0,
CLASSPATH=/home/jenkins/workspace/Grinder/etc, LANG=en_US.UTF-8,
HOME=/home/jenkins}
```
The default OpenJ9 options produce unnecessary system dumps which are
multi GB in size. When failures occur or results are archived, the
system dumps bloat the size of the result artifact, consuming more space
and increasing download times.
See also https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/404
Tested via https://ci.eclipse.org/openj9/view/Test/job/Grinder/837
=> Modify ProcessBuilder/Basic test options to avoid dumps for OOM

closed/OpenJ9.gmk, closed/autoconf/custom-hook.m4, closed/autoconf/custom-spec.gmk.in, closed/autoconf/toolchain-win.cmake.in
On some platforms (osx, windows), CMake uses a hardcoded search path
rather than walking $PATH. To make sure that we use the version of
NASM that we tested, manually sed the cache variable (as we do for the
C/C++ compilers)
=> CMake: Ensure cmake uses the NASM executable that we tested

closed/autoconf/custom-hook.m4
Move the message to inside the conditional where we actually check for
freemarker. Currently if  cmake is enabled, a message about checking
for freemarker is emitted, but no check is performed, and no response
emitted.
=> Move message about checking for freemarker

closed/autoconf/custom-hook.m4
This reverts commit dd161e98f9007f85e629409a1feeeb3370828e96.
=> Revert "Rename OpenJ9 build specs for Linux PPC LE platforms"

closed/DDR.gmk
A replay of ibmruntimes/openj9-openjdk-jdk11#302 for jdknext.
=> Fix DDR compile error due to ibm.jzos

closed/autoconf/custom-hook.m4
Rename OPENJ9_BUILDSPEC for the Linux PPC LE, remove _gcc from their
names.
Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>
=> Rename OpenJ9 build specs for Linux PPC LE platforms

closed/autoconf/custom-hook.m4
This commit adds aarch64 as an acceptable CPU name in custom-hook.m4.
Signed-off-by: KONNO Kazuhiro <konno@jp.ibm.com>
=> Add aarch64 to custom-hook.m4

closed/DDR.gmk
Adapt organization of makefiles for:
8244044: Refactor phase makefiles to be structured per module
The `ADD_JAVAC_FLAGS` argument to `SetupJavaCompilation` has been renamed to `JAVAC_FLAGS` (this change was missed in #202).
Note this is a merge to the openj9-staging branch.
=> Update makefiles for recent openjdk changes (part 2)

closed/custom/Main.gmk
Configure sets `BUILD_FAILURE_HANDLER` to true or false dependending on whether `JT_HOME` is set or not. In our builds `configure` says:
```
checking if the jtreg failure handler is available... no (jtreg not present)
checking if the jtreg failure handler should be built... disabled, from default 'auto'
```
The dependency
```
test-image : test-image-failure-handler
```
is unconditional, but the rule for `test-image-failure-handler` is only declared if `BUILD_FAILURE_HANDLER` is true. The declaration that it is a `.PHONY` target is also conditional.
This works around that deficiency of openjdk makefiles.
Note this is a merge to the openj9-staging branch.
=> Workaround missing rule for test-image-failure-handler

closed/src/java.base/share/classes/com/sun/crypto/provider/NativeChaCha20Cipher.java
Fixing OpenJ9 Issue #9429.
I added a special case in the ChaCha20 update function: when the size returned by the doUpdate is zero, the function must return a new zero-sized array since the input was only buffered and nothing was encrypted.
Equivalent to [OpenJDK11 PR](https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/305) but for JDK.
Signed-off-by: Samer AL Masri <samasri@ibm.com>
=> Added special case for EngineAEADDec in engineUpdate

closed/autoconf/custom-spec.gmk.in
It was renamed by:
* [8244951: Missing entitlements for hardened runtime](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/99b7777)
=> Update codesign entitlements file name

closed/test/jtreg-ext/jtreg/openj9/CoreDumpTimeoutHandler.java
The timeout handler can be used via command line options with the jtreg
harness when running openjdk tests. It uses OpenJ9 APIs (`jcmd
Dump.system`) to request a system dump when a timeout occurs, in
addition to running jstack as the default handler does.
See the original DefaultTimeoutHandler
https://hg.openjdk.java.net/code-tools/jtreg/file/d92197d367e3/src/share/classes/com/sun/javatest/regtest/exec/DefaultTimeoutHandler.java
A jar will be created via a Jenkins job, and then used to run openjdk tests.
https://ci.eclipse.org/openj9/view/Infrastructure/job/Build_JDK_Timeout_Handler/
Issue https://github.com/eclipse/openj9/issues/9651
=> Create a custom jtreg timeout handler

src/java.base/share/classes/java/lang/invoke/StringConcatFactory.java
OpenJ9 does not support MethodHandle.rebind. So, its usage has been temporarily
removed from StringConcatFactory until OpenJ9 supports OpenJDK MethodHandles.
Fixes: eclipse/openj9#9771
Identical to https://github.com/ibmruntimes/openj9-openjdk-jdk15/pull/4.
=> Do not use rebind in StringConcatFactory

src/jdk.compiler/share/classes/com/sun/tools/javac/comp/LambdaToMethod.java
When javac creates the `deserializeLambda` method, the `externalize` method is
called on the class names needed in order to swap the `.` and `/` characters.
This is returned as a byte array, which is turned into a string by calling the
String constructor. However, the bytes are encoded in the JVM's UTF encoding,
which can result in the String constructor making a bad string if the platform
default encoding has different byte values for characters.
This commit uses the `Names.fromUtf` method also used in ClassWriter.java for
dealing with the externalized class names instead of the String constructor.
Signed-off-by: Mike Zhang <mike.h.zhang@ibm.com>
Fix for https://github.com/eclipse/openj9/issues/9168
=> Fix deserializeLambda being generated with bad string encoding

closed/CopySupport.gmk
Also include OpenJ9 `.map` files on Windows; see eclipse/openj9#10099.
=> Expand content of debug images

closed/custom/modules/java.base/Copy.gmk
Pick the first file found out of
- options.default-$(VERSION_FEATURE)-$(OPENJDK_TARGET_OS)
- options.default-$(VERSION_FEATURE)
- options.default
Similar changes to https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/330
=> Support version and OS specific options.default in the build

closed/autoconf/custom-spec.gmk.in
There will be no warnings in openj9.dataaccess or openj9.jvm to be ignored after eclipse/openj9#10270 and eclipse/openj9#10271 are merged: this will contribute to ensuring it stays that way.
=> Stop ignoring warnings from openj9.dataaccess and openj9.jvm

closed/DDR.gmk
Update path to ibm.jzos source files since openj9/jcl/src/ibm.jzos has
moved to openj9/jcl/stubs.
Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>
=> Update source path for DDR stubs target

closed/OpenJ9.gmk
Added INLINETYPES version flag to pre-processor for use as Java flag,
depends on Java15 version.
Related to: https://github.com/eclipse/openj9/issues/10078
Depends on: https://github.com/eclipse/openj9/pull/10337
Signed-off-by: Oussama Saoudi <oussama.saoudi@ibm.com>
=> Add INLINE-TYPES flag pre-processor

buildenv/jenkins/jobs/infrastructure/copyrightCheckDir.sh
https://github.ibm.com/runtimes/openjdk-contribution/issues/1246
excluding jdk/test in script.
Raising with OpenJDK as well in sametime. Locally tested the changes and
it works.
=> Copyrights JDK8 : Found Oracle Proprietary copyright under jdk/test

closed/custom/modules/java.base/Copy.gmk
Also include epl license which the OpenJ9 license refers to.
Same change as https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/344/
=> For easier reading, use OpenJ9 text instead of html license

src/java.base/aix/classes/jdk/internal/loader/ClassLoaderHelper.java
**Implement ClassLoaderHelper.mapAlternativeName() for AIX .a library**
Create `java.base/aix/classes/jdk/internal/loader/ClassLoaderHelper.java`;
Replace the final `.so` suffix with `.a` for `AIX` platform.
Verified that with this PR, `-version` still runs successfully after renaming `libnio.so` to `libnio.a`, w/o it, `UnsatisfiedLinkError` occurs as following:
```
Exception in thread "main" java/lang/UnsatisfiedLinkError: sun/nio/fs/UnixNativeDispatcher.init()I
at sun/nio/fs/UnixNativeDispatcher.<clinit> (java.base@9/UnixNativeDispatcher.java:654)
at sun/nio/fs/UnixFileSystem.<init> (java.base@9/UnixFileSystem.java:65)
at sun/nio/fs/AixFileSystem.<init> (java.base@9/AixFileSystem.java:42)
at sun/nio/fs/AixFileSystemProvider.newFileSystem (java.base@9/AixFileSystemProvider.java:42)
at …
```
=> Implement ClassLoaderHelper.mapAlternativeName() for AIX .a library

buildenv/jenkins/jobs/infrastructure/copyrightCheckDir.sh
https://github.ibm.com/runtimes/javanext/issues/235
=> The exclusion as know issue was done only for jdk8 and not for jdk 15.

closed/OpenJ9.gmk, src/java.base/share/lib/security/default.policy
* don't define unused preprocessor macro `com.ibm.oti.vm.library.version`
* remove unnecessary read permission for `com.ibm.oti.vm.library.version`
Depends on eclipse/openj9#10888.
=> Remove references to 'com.ibm.oti.vm.library.version'

closed/OpenJ9.gmk, closed/autoconf/custom-spec.gmk.in, closed/custom/Main.gmk
This is essentially a replay of ibmruntimes/openj9-openjdk-jdk11#355, eliminating unnecessary differences relative to Java 11.
=> Improve integration with openjdk build system

closed/src/java.base/share/native/libjava/PhantomReference.c, closed/src/java.base/share/native/libjava/Reference.c
Recently added in Java 16 is `Reference.refersTo(Object)`; the openjdk natives are inappropriate for use with OpenJ9 which has it's own implementation of `Reference` and `PhantomReference`. These empty files suppress use of the openjdk native code.
```
23:20:42  ./src/java.base/share/native/libjava/PhantomReference.c:27:10: fatal error: java_lang_ref_PhantomReference.h: No such file or directory
23:20:42   #include "java_lang_ref_PhantomReference.h"
23:20:42            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Note this targets the openj9-staging branch.
Fixes https://github.com/eclipse/openj9/issues/11119
=> Add empty files PhantomReference.c and Reference.c

closed/GensrcJ9JCL.gmk, closed/OpenJ9.gmk, closed/autoconf/custom-spec.gmk.in, closed/custom/Docs.gmk, closed/custom/Main.gmk, closed/custom/common/Modules.gmk
* move j9jcl preprocessing to a separate makefile to enable reuse to ensure `module-deps.gmk` is based on the right set of modules
* remove redundant definition of FixPath
* remove unused macro OPENJ9_BIN_OR_LIB_DIR
The OpenJDK build system supports [multiple configurations](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/master/doc/building.md#using-multiple-configurations).
One example use might be building both with UMA and with cmake (while cmake development is ongoing):
```
$ bash configure --with-cmake --with-conf-name=cmake
$ bash configure --with-freemarker-jar=$HOME/freemarker.jar --with-conf-name=uma
```
Or you might be working on code sensitive to how references are represented [1]:
```
$ bash configure --with-cmake --with-conf-name=normal
$ bash configure --with-cmake …
```
=> Improve support for builds with multiple configurations

closed/custom/common/Modules.gmk
Referring to https://openjdk.java.net/jeps/261 modules which are part of
the java platform, and not tools, should be platform modules. In
particular this is a problem for the ibm.jzos platform module which
requires openj9.dataaccess.
=> Add OpenJ9 modules as platform modules

closed/test/jtreg-ext/requires/OpenJ9PropsExt.java
Set vm.bits property to be available in the @requires expressions
Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>
=> Set vm.bits property

closed/DDR.gmk
`PATH_SEP` has been removed, use `PathList` call instead.
With this PR, `JDK16` builds and `-version` output is as following:
```
openjdk version "16-internal" 2021-03-16
OpenJDK Runtime Environment (build 16-internal+0-adhoc.fengjcaibmcom.openj9-openjdk-jdk)
Eclipse OpenJ9 VM (build moduleread-e28ba30599, JRE 16 Mac OS X amd64-64-Bit Compressed References 20201208_000000 (JIT enabled, AOT enabled)
OpenJ9   - e28ba30599
OMR      - da9530688
JCL      - 0e3d8884eda based on jdk-16+27)
```
closes https://github.com/eclipse/openj9/issues/11402
fyi @tajila 
=> Replace obsoleted PATH_SEP with PathList call

src/java.base/share/classes/jdk/internal/loader/URLClassPath.java
When reaching URLClassPath.getLoader() before module system is
initialized, usingSharedClasses() always returns false. It is
likely that SCC support is not initialized for BuiltinClassLoaders
yet, which is done during module system initialization. We still need
to update loaderURLs in this case.
issue eclipse/openj9#11342
Signed-off-by: Hang Shao <hangshao@ca.ibm.com>
=> Do not rely on usingSharedClasses() to add url to loaderURLs

closed/make/modules/openj9.dtfjview/Launcher.gmk
Otherwise IllegalAccessError occurs with the new default
`--illegal-access=deny`.
Issue https://github.com/eclipse/openj9/issues/11445
=> Export com.ibm.dtfj.utils so jdmpview can work

make/common/Modules.gmk
Adjust the order to setup module sets for classloaders first, then call hook to include the corresponding custom file, if present.
Verified manually (`Mac OSX` platform) that this fixes the issue reported via https://github.com/eclipse/openj9/issues/11512
~Note: latest `openj9-staging` branch still fails due to https://github.com/eclipse/openj9/issues/11515.~
closes https://github.com/eclipse/openj9/issues/11512
=> Hook to include custom file should follow module setup for classloader

closed/CopySupport.gmk, closed/GensrcJ9JCL.gmk, closed/OpenJ9.gmk, closed/autoconf/custom-hook.m4, closed/autoconf/custom-spec.gmk.in, make/scripts/fixpath.sh
* fix handling of relative paths by `fixpath.sh`; we don't want to map arguments like
`-I../../include`
to
`-I..C:\cygwin\..\include`
The original version treated the first slash as if it were the beginning of an absolute path.
* update the use of `buildj9tools.mk` to build the java preprocessor to avoid issues due to changes to `FixPath`
* compute `OPENJ9_VS_INCLUDE` and `OPENJ9_VS_LIB` and make available for substitutions (replacing `VS_INCLUDE` and `VS_LIB`)
* remove redundant exports
- `INCLUDE` and `LIB` are exported by `custom-spec.gmk`
* adjust macro references
- `CYGPATH`    -> `PATHTOOL`
- `EXE_SUFFIX` -> `EXECUTABLE_SUFFIX`
=> Adapt to recent openjdk changes

closed/make/modules/openj9.dtfjview/Launcher.gmk
Now done programmatically in `com.ibm.dtfj.image.j9.ImageFactory` via eclipse/openj9#11597.
=> Revert '--add-exports=openj9.dtfj/com.ibm.dtfj.utils=ALL-UNNAMED'

closed/DDR.gmk
Required when using a Java 16+ boot jdk (where the default `--illegal-access=deny` applies).
See eclipse/openj9#11613.
=> Export jdk.internal.org.objectweb.asm for ClassGenerator

make/CompileJavaModules.gmk, make/Main.gmk
The pre-hook and post-hook in `CompileJavaModules.gmk` were removed by
* 8258407 Split up CompileJavaModules.gmk into make/modules/$M/Java.gmk
and the include directive for `Java.gmk` uses an absolute path leaving no path to customizations. This updates `Main.gmk` to define an include path based on `PHASE_MAKEDIRS` for make as was done for other phases in
* 8252998 ModuleWrapper.gmk doesn't consult include path
This is required by part of the anticipated fix for eclipse/openj9#11464.
=> Use $(PHASE_MAKEDIRS) for the Java phase for consistency

make/autoconf/lib-bundled.m4, src/java.base/unix/native/libjli/java_md.c, src/java.base/unix/native/libjli/java_md.h
zlibNX is an accelerated replacement for zlib, it make use of the NX accelerator in P9 and newer systems.
This PR enable the use of zlibNX for AIX systems by adding it to the LIBPATH if the system is P9 or newer and has the NX accelerator enabled.
This PR also sets system zlib as default instead of bundled zlib on AIX systems to allow zlibNX
For reference, the change to bundle zlib on AIX is https://bugs.openjdk.java.net/browse/JDK-8223685
Signed-off-by: Abdulrahman Alattas rmnattas@gmail.com
=> Add accelerated zlibNX to LIBPATH for AIX P9 or newer systems and set system zlib as default on AIX

closed/custom/modules/java.base/Copy.gmk
Port of: https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/378
For: https://github.com/eclipse/openj9/pull/11662
Includes the j9vrb_full library in the JDK for mixed references builds.
=> Include j9vrb_full library in mixed references builds

make/common/Modules.gmk
The JCL patch is invalid after JDK-8260289 has been contributed as https://github.com/openjdk/jdk/pull/2219
=> Remove JCL patch after contribution of JDK-8260289

closed/DDR.gmk, closed/custom/Main.gmk, closed/make/modules/openj9.dtfj/Gensrc.gmk, closed/make/modules/openj9.dtfj/Java.gmk
* generate content in `gensrc` phase
* expect `openj9.dtfj` to host `ZFile` stub class when appropriate
Part of the solution for eclipse/openj9#11464.
Depends on, and must be merged at the same time as, eclipse/openj9#11735.
=> Refactor content of j9ddr.jar into module openj9.dtfjview

src/java.base/share/classes/java/lang/StringCoding.java
Assume this is an intermediate approach to unblock JDK17 abuild.
Note: this `StringCoding.java` is same as the one in `openj9` branch.
With this PR, JDK17 builds and `-version` output is:
```
openjdk version "17-internal" 2021-09-14
OpenJDK Runtime Environment (build 17-internal+0-adhoc.fengjcaibmcom.openj9-openjdk-jdk)
Eclipse OpenJ9 VM (build master-2a86052a48, JRE 17 Mac OS X amd64-64-Bit Compressed References 20210128_000000 (JIT enabled, AOT enabled)
OpenJ9   - 2a86052a48
OMR      - 9da8f8acb
JCL      - addc8eec6a7 based on jdk-17+6)
```
depends: this PR depends on the latest merging job to include `jvm_constants.h` & `jvm_io.h`.
Closes https://github.com/eclipse/openj9/issues/11758
=> Restore legacy StringCoding to accommodate OpenJ9 String

closed/DDR.gmk, closed/make/modules/openj9.dtfj/Gensrc.gmk
* avoid race creating directories when DDR is enabled
* do nothing for openj9.dtfj-gensrc-src when DDR is disabled
See: eclipse/openj9#11818; depends on eclipse/openj9#11824.
=> Fix DDR-related build issues

closed/DDR.gmk
Note: This targets the openj9-staging branch and depends on eclipse/openj9#11888.
=> Add required javac flags for building DDR tools

test/jdk/java/foreign/TestLibraryLookup.java
This is to accommodate OpenJ9 aggressive GC polices.
Related https://github.com/eclipse/openj9/issues/11838
=> Use Reference.reachabilityFence to keep the object alive

closed/autoconf/custom-hook.m4, closed/autoconf/toolchain-win.cmake.in
- Enable using clang to compile the interpreter
- Update tool wrappers to work with new fixpath
=> Update CMake Windows support

closed/autoconf/custom-hook.m4
This is so far untested, although jdk16 looks good https://github.com/ibmruntimes/openj9-openjdk-jdk16/pull/20#issue-570744853
=> Enable cmake for AIX by default

closed/src/java.base/share/classes/com/sun/crypto/provider/NativeGaloisCounterMode.java, src/java.base/share/classes/com/sun/crypto/provider/CipherCore.java, test/jdk/com/sun/crypto/provider/Cipher/AEAD/GCMBufferTest.java
Fixing [OpenJ9's Issue 11390](https://github.com/eclipse/openj9/issues/11390). Specifically, some of the AEAD tests were failing in the jtreg test harness. This PR fixes them by:
* Adding necessary functions to `NativeGaloisCounterMode` to support processing ByteBuffer input and output.
* Editing the jtreg test _GCMBufferTest.java_ to not check for the output length after `cipher.update`. This is because `cipher.update` doesn't have to return the encrypted input length. In our JDK, the `cipher.update` behaves differently depending on whether the machine used does have native crypto or not:
* If native crypto is used, the `cipher.update` processes the input by adding it to a buffer, which will be processed when `cipher.doFinal` is called. Hence, the `cipher.update` returns zero.
* However, …
=> Enhancing GCM ByteBuffer Implementation

closed/autoconf/custom-hook.m4
See https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/382
=> Default jdk17 to build mixedrefs, unless cross compiling

closed/custom/CreateJmods.gmk
All of the classes in the `com.ibm.j9ddr.vm29.structure` package are derived at runtime from the related core file and so do not need to be included in the `openj9.dtfj` module.
The `module-info` class file lists `com/ibm/j9ddr/vm29/structure` as a package defined by that module, so we retain one class (`DDRAlgorithmVersions`) to avoid an inconsistency.
The net effect of this change is to reduce the size of the `modules` file by about 2MB which may reduce the physical memory required by the VM.
=> Remove many unnecessary classes from openj9.dtfj

closed/custom/Docs.gmk
Among other errors (being addressed via eclipse/openj9#12134), building javadocs in the openj9-staging branch complains:
```
JDK_API-overview.html:1: error: attribute lacks value
```
This corrects that (by referring to a make variable that is defined).
=> Correct href URL in javadoc for OpenJ9 project

closed/custom/Docs.gmk
Many javadoc issues are addressed by eclipse/openj9#12134; this will allow the openj9 branch to promote while we fix the remaining ones.
Note this targets the openj9-staging branch.
=> Temporarily disable some javadoc diagnostics for OpenJ9

closed/DDR.gmk, closed/make/modules/openj9.dtfj/Java.gmk
This is part of the solution to eclipse/openj9#12182; it depends on eclipse/openj9#12210.
* compile using only those constants guaranteed to be available
* include `CompatibilityConstants29.dat` in `openj9.dtfj` module
=> Improve backward compatibility of openj9.dtfj

test/jdk/java/lang/ProcessBuilder/Basic.java
On a 64GB machine the test fails to throw OOM using OpenJ9, and fails
the test. Set the max heap to 500MB.
Issue eclipse/openj9#12216
Same change as https://github.com/ibmruntimes/openj9-openjdk-jdk16/pull/39, I didn't re-test.
=> Update ProcessBuilder/Basic test to limit heap memory

closed/test/jtreg-ext/requires/OpenJ9PropsExt.java
- Add vm.hasJFR parameter for openj9, which is required by jdk_io GlobalFilterTest
- Related Issue: https://github.com/eclipse/openj9/issues/12079
=> Fix jdk_io GlobalFilterTest for JDK17

closed/custom/Docs.gmk
Renamed upstream from `JAVADOC_DISABLED_DOCLINT` to `JAVADOC_DISABLED_DOCLINT_WARNINGS` in
* 8263827: Suspend "missing" javadoc doclint checks for smartcardio
~Note: this targets the `openj9-staging` branch.~
=> Fix reference to JAVADOC_DISABLED_DOCLINT_WARNINGS

closed/test/jtreg-ext/requires/OpenJ9PropsExt.java
- Add vm.compiler2.enabled parameter for openj9, which is required by jdk_vector PreferredSpeciesTest
- Related Issue: https://github.com/eclipse/openj9/issues/12270
=> Fix jdk_vector PreferredSpeciesTest for JDK17

closed/autoconf/custom-hook.m4, closed/autoconf/custom-spec.gmk.in, closed/custom/Main.gmk, closed/custom/common/Modules.gmk, closed/make/modules/ibm.healthcenter/Copy.gmk, closed/src/ibm.healthcenter/share/classes/module-info.java, src/java.base/share/lib/security/default.policy
* unpack artifacts from archive named via `--with-healthcenter` option
* set default transport to `jrmp`
* add to list of platform modules
* add required security permissions
This is a replay of ibmruntimes/openj9-openjdk-jdk11#395 for Java 17.
=> Support including healthcenter agent module

closed/make/modules/jdk.jcmd/Launcher.gmk, closed/make/modules/openj9.dtfj/Launcher.gmk, closed/make/modules/openj9.dtfjview/Launcher.gmk, closed/make/modules/openj9.traceformat/Launcher.gmk
`MAIN_MODULE` only needs to be specified when the main class is not in the current module.
This is a replay of ibmruntimes/openj9-openjdk-jdk11#397 for Java 17.
=> Remove redundant launcher specifications of MAIN_MODULE

closed/make/modules/openj9.dtfj/Launcher.gmk
Equivalent to `jextract` which will clash with an upstream tool.
See eclipse/openj9#11278.
=> Add new jpackcore launcher

src/java.base/share/classes/java/lang/String.java, src/java.base/share/classes/java/lang/StringCoding.java
Add OpenJ9 specific fields/methods into RI `java.lang.String`;
Make `StringCoding.implEncodeISOArray()` `public` which is required by RI `String`;
A separated PR (https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/296) is to remove legacy `StringCoding` code.
Note: this change to `java.lang.String` has no impact on current JDK17 build cause it is not included by OpenJ9 yet.
This unlocks https://github.com/eclipse/openj9/pull/12209.
=> OpenJ9 Adopts RI java.lang.String

closed/autoconf/custom-hook.m4
Fixes: https://github.com/eclipse/openj9/issues/12524
=> Enable OpenJDK MHs for OpenJ9 JDK17 by default

closed/autoconf/custom-hook.m4
It used to say:
>  checking for openjdk-methodhandles... yes (default for )
This removes the ' for ' part:
> checking for openjdk-methodhandles... yes (default)
Note this targets the openj9-staging branch.
=> Fix feedback for '--enable-openjdk-methodhandles'

closed/OpenJ9.gmk
Allow compiler options to follow input file names. This is needed for
CMake builds.
Port of https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/405 and https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/406
#	closed/OpenJ9.gmk
=> Allow more flexible compiler invocations on z/OS

closed/DDR.gmk, closed/make/modules/openj9.dtfj/Java.gmk
This updates the build steps for DDR code to properly handle optional fields.
This depends on eclipse-openj9/openj9#12676.
=> DDR: do test compile with minimal set of fields

test/jdk/java/util/zip/DeInflate.java
test/jdk/java/util/zip/DeInflate.java
Issue eclipse-openj9/openj9#12740
Port of https://github.com/ibmruntimes/openj9-openjdk-jdk11
It's the same change so I don't think it needs testing, but let me know if you want a grinder.
=> In test, increase deflate buffer size for zlinux Ubuntu 20

closed/make/modules/ibm.healthcenter/Copy.gmk
Otherwise, `sed` will not properly interpret its contents.
=> Ensure healthcenter.properties file is properly encoded on z/OS

closed/src/java.base/share/native/libjncrypto/NativeCrypto.c
This PR fixes part of eclipse-openj9/openj9#11500 by changing the way verification is implemented in the RSADP operation.
More specifically, this PR adds a special case when verifying a message. For certain key sizes (where keySize % 8 == 1), the decrypted message retrieved from the `RSA_public_decrypt` includes a 1 byte padding at the beginning of the message. In these cases, this padding must be ignored when comparing the decrypted message to the original message.
Signed-off-by: Samer AL Masri <samasri@ibm.com>
=> Handle Exceptional Padding Cases in the Native RSADP Verification

src/java.base/share/classes/java/lang/invoke/MethodHandles.java
The change is to fix the bug with the return type of the omitted
finalizers as OpenJDK doesn't follow the Spec to set the loop
return type.
=> [JDK17] Fix the bug with the return type of the omitted finalizers in loop

closed/custom/Main.gmk
Dependency is expressed via macro `JVM_TEST_IMAGE_TARGETS`.
=> Remove redundant dependency

closed/DDR.gmk, closed/make/modules/openj9.dtfj/Java.gmk
The files were removed by eclipse-openj9/openj9#13045.
=> Remove exclusions for removed ant tasks

closed/custom/common/Modules.gmk
Put openj9.criu in the boot modules list
The openj9.criu natives are located in the jclse29 dll. The jclse29
library is loaded by the system loader, this means that only classes
that are loaded by the system loader can access natives in this library.
Currently the openj9.criu module is in the platform modules list, as a
result it is loaded by the platform loader and not the system loader.
Therefore it is unable to access the natives in jclse29. This PR puts
openj9.criu in the bootmodule list so it can access the jclse29 natives.
Signed-off-by: Tobi Ajila <atobia@ca.ibm.com>
=> Put openj9.criu in the boot modules list 

buildenv/jenkins/jobs/infrastructure/copyrightCheckDir.sh
Excluded hotspot and gpl-header template files into copyright script.
https://openj9-jenkins.osuosl.org/view/Infrastructure/job/CopyrightCheck-OpenJDK17/10/
@Peter-Shipton : These seem to be hotspot related which need to add to the script as an excluded. Please if you can confirm that and I can update the script file.
20:59:37  E012: make/data/hotspot-symbols/symbols-aix: GPLv2 is present but Classpath exception is missing
20:59:37  Did not find make/data/hotspot-symbols/symbols-aix in known failures file /home/jenkins/jenkins-agent/workspace/CopyrightCheck-OpenJDK17/workdir/ibmruntimes/openj9-openjdk-jdk17.git/copyrightCheck.known.failures, treating as error
20:59:37  E012: make/data/hotspot-symbols/symbols-aix-debug: GPLv2 is present but Classpath exception is missing
20:59:37  Did not …
=> JDK17 Copyright issues fixed in script

make/common/modules/LauncherCommon.gmk
On some machines the java launcher is loaded around 0x100000000,
breaking up the address space.
Port of https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/518
=> Set default load address for launchers on plinux

test/jdk/java/lang/ProcessBuilder/Basic.java
Remove `-Xlog:all` not supported by OpenJ9
Cherry-pick from https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/12
=> Remove -Xlog:all not supported by OpenJ9

closed/test/jtreg-ext/requires/OpenJ9PropsExt.java
Support eclipse-openj9/openj9#12276
Similar change as ibmruntimes/openj9-openjdk-jdk16#72 https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/13
=> Set system property vm.jvmti to true

closed/custom/modules/java.base/Copy.gmk
Enables alternate builds such as mixed refs on z/OS without hard coding
the VM dir, compressedrefs or default.
Same change as https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/14
=> Add libj9a2e.so to lib directory

closed/make/modules/openj9.criu/Copy.gmk
Added j9criu29 as one of the generated libraries to copy over
Depends on: eclipse-openj9/openj9#13245
Signed-off-by: Oussama Saoudi <oussama.saoudi@ibm.com>
=> Add copy for openj9.criu module to load j9criu library

closed/src/java.base/share/classes/com/sun/crypto/provider/NativeGaloisCounterMode.java, src/java.base/share/classes/com/sun/crypto/provider/SunJCE.java
Change NativeGaloisCounterMode to extend CipherSpi instead of FeedbackCipher and override the associated abstract methods. Add the inner class GCMEngine and its two subclasses GCMEncrypt and GCMDecrypt.
Modify SunJCE to allow it to call NativeGaloisCounterMode.
Signed-off-by: Zainab Fatmi <zainab@ibm.com>
=> Re-enable native GCM

closed/OpenJ9.gmk
Ensure that --disable-warnings-as-errors-omr and
--disable-warnings-as-errors-openj9 get passed to cmake.
=> CMake: honor --disable-warnings-as-errors-<X> flags

closed/autoconf/custom-spec.gmk.in
For releases, the value is hard-coded, otherwise it is redefined on the following line.
=> Remove unused definition of J9JDK_EXT_VERSION

src/java.base/share/classes/sun/nio/cs/US_ASCII.java
Recent upstream changes should eliminate the benefit of changes specific to OpenJ9.
=> Undo changes to US_ASCII for OpenJ9

src/java.base/aix/classes/jdk/internal/loader/ClassLoaderHelper.java
Required by `NativeLibraries.loadLibraryOnlyIfPresent = ClassLoaderHelper.loadLibraryOnlyIfPresent()` which is introduced by `8275703: System.loadLibrary fails on Big Sur for libraries hidden from filesystem`.
fixes https://github.com/eclipse-openj9/openj9/issues/13827 
=> Add loadLibraryOnlyIfPresent to adopt NativeLibraries changes

closed/custom/modules/java.base/Copy.gmk
- Copy the customized JNI header files to include31 directory to JDK_IMAGE base directory.
- Copy the libjvm31.so library and libjvm31.x sidedeck to server / j9vm.
Signed-off-by: Joran Siu <joransiu@ca.ibm.com>
=> zOS: Add 31/64-bit interoperability staging

test/jdk/jdk/internal/reflect/Reflection/GetCallerClassTest.java
InternalError message in GetCallerClassTest differs between JVMs:
- OpenJ9: "Caller is not annotated as @sun.reflect.CallerSensitive"
- OpenJDK: "CallerSensitive annotation expected"
GetCallerClassTest has been updated to accept OpenJ9's InternalError message.
Closes: https://github.com/eclipse-openj9/openj9/issues/13998
=> GetCallerClassTest: Accept OpenJ9's InternalError Message

closed/src/java.base/share/classes/java/io/ClassNameCache.java, src/java.base/share/classes/java/io/ObjectInputStream.java
Renamed `ClassCache` to `ClassNameCache` to avoid name collision with `OpenJDK` `java.io.ClassCache` introduced by JDK-8199589 : `ObjectStreamClass` does not provide a mechanism to clear the cache.
=> JDK19 bringup

test/jdk/java/lang/Object/FinalizationOption.java
`OpenJ9` `Finalization` thread name is `Finalizer thread`.
related to https://github.com/eclipse-openj9/openj9/issues/14049
fyi @dmitripivkine
=> OpenJ9 Finalization thread name is "Finalizer thread"

test/jdk/java/lang/Object/InvalidFinalizationOption.java
Use `OpenJ9` error message - `Command-line option unrecognised`
Porting from https://github.com/ibmruntimes/openj9-openjdk-jdk18/pull/8
=> Use OpenJ9 error message - Command-line option unrecognised

closed/test/jtreg-ext/requires/OpenJ9PropsExt.java
- Fix NativeLibraryTest for JDK 19
- Related Issue: https://github.com/eclipse-openj9/openj9/issues/14349
=> Fix NativeLibraryTest for JDK 19

test/jdk/java/util/Properties/PropertiesStoreTest.java, test/jdk/java/util/Properties/StoreReproducibilityTest.java
The properties date comment is parsed based on the JVM locale settings
which may cause it to fail since the date comment is always written as
if the locale were en_US. Thus, force the tests to use en_US or root
locale.
Signed-off-by: Mike Zhang <mike.h.zhang@ibm.com>
Also fixes https://github.com/eclipse-openj9/openj9/issues/14226
fyi: @pshipton
=> Force properties date tests to use non-conflicting locale

test/jdk/java/lang/Object/FinalizationOption.java
In test java/lang/Object/FinalizationOption.java
Port of https://github.com/ibmruntimes/openj9-openjdk-jdk18/pull/18 to the head stream.
Issue https://github.com/eclipse-openj9/openj9/issues/14491
=> Fix test to check for finalizer thread after object finalized

src/jdk.incubator.foreign/share/classes/jdk/incubator/foreign/CLinker.java, src/jdk.incubator.foreign/share/classes/jdk/incubator/foreign/VaList.java, src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/CABI.java, src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/PlatformLayouts.java, src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/SystemLookup.java, src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/SharedUtils.java, src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/aarch64/CallArranger.java, src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/ppc64/aix/AixPPC64Linker.java, src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/ppc64/aix/AixPPC64VaList.java, src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/ppc64/aix/CallArranger.java, src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/ppc64/sysv/CallArranger.java, src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/ppc64/sysv/SysVPPC64leLinker.java, src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/ppc64/sysv/SysVPPC64leVaList.java, src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/s390x/sysv/CallArranger.java, src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/s390x/sysv/SysVS390xLinker.java, src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/s390x/sysv/SysVS390xVaList.java, src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/x64/sysv/CallArranger.java, src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/x64/windows/CallArranger.java
The changes aim to enable the CLinker downcall handle to support
primitives and struct on AIX/ppc64, Linux/ppc64le and Linux/s390x
by invoking the code in ProgrammableInvoker implemented in OpenJ9.
=> [JDK_HEAD] Implement the CLinker downcall handle of JEP389/419 on PPC64/S390

src/java.base/share/classes/java/lang/Thread.java
Refactoring `Thread` to simplify RI `java.lang.Thread` adoption.
Depends on https://github.com/eclipse-openj9/openj9/pull/14852
=> Move Thread.completeInitialization() into J9VMInternals

closed/make/modules/openj9.dtfj/Gensrc.gmk
The include file was renamed by
* 8284588: Remove GensrcCommonLangtools.gmk
=> Adapt to rename of GensrcCommonJdk.gmk to GensrcCommon.gmk

closed/GensrcJ9JCL.gmk, src/java.base/unix/classes/java/lang/ProcessEnvironment.java
Cherry-pick https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/486
CRIU support: add checkpoint/restore environment variables
Added `isCRIUEnabled` via `CRIUProvider.getOpenJ9CRIU()`;
Added `tracePrunedEnvVarsValue` via `org.eclipse.openj9.criu.TracePrunedEnvVars`;
Added `theOriginalUnmodifiableEnvironment` to store original `theUnmodifiableEnvironment`;
Hard-coded immutable list: `LANG`, `LC_ALL` and `LC_CTYPE`;
https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/498
Copy `$(TOPDIR)/src/java.base/unix/classes/java/lang/ProcessEnvironment.java` to `$(SUPPORT_OUTPUTDIR)/overlay/src/java.base/unix/classes/java/lang`;
Decorate `ProcessEnvironment.java` CRIU specific code with `CRIU_SUPPORT` JPP flag.
fyi @tajila 
=> CRIU support w/ JPP : add checkpoint/restore environment variables

closed/autoconf/custom-hook.m4
The default for configure option `--with-output-sync` changed to `recurse` with
* 8285093: Introduce UTIL_ARG_WITH
In a nightly build, for example, we see:
```
21:32:39  checking if make --output-sync is supported... no
21:32:39  check msg:for make --output-sync value:
21:32:39  checking for make --output-sync value... <invalid>, not available
```
but with a new version of make, that supports `-O`, the output for building the VM appears as a single chunk of output, giving the appearance that it has stalled.
This changes it back to `none`.
=> Restore build progress for OpenJ9 VM

closed/GensrcJ9JCL.gmk
This matches `$(TOPDIR)/closed`.
Cherry-pick https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/501
=> Add IncludeIfUnsure for $(SUPPORT_OUTPUTDIR)/overlay

closed/src/java.base/share/classes/java/io/ClassByNameCache.java
The copyright date was missed in #438, perhaps because the file was renamed.
=> Fix copyright date, replace tab with spaces

closed/test/jtreg-ext/requires/OpenJ9PropsExt.java
- Fix jdk_verctor vm.gz.Z value
- Related Issue: https://github.com/eclipse-openj9/openj9/issues/15064
=> Fix jdk_verctor vm.gz.Z value for jdknext

closed/autoconf/custom-hook.m4
Issue https://github.com/ibmruntimes/openj9-openjdk-jdk/issues/422
=> Default to using cmake on cross-compiles

buildenv/jenkins/jobs/infrastructure/copyrightCheck
Copyright checking often fails because 10 minutes isn't always enough.
=> Increase clone timeout to 30 minutes

closed/test/jtreg-ext/requires/OpenJ9PropsExt.java, test/jdk/TEST.ROOT, test/jdk/jdk/internal/vm/Continuation/HumongousStack.java
- Add vm.continuations and vm.openj9 value
- Related Issue: https://github.com/eclipse-openj9/openj9/issues/15189  https://github.com/eclipse-openj9/openj9/issues/15247
=> Add vm.continuations and vm.openj9 value

src/java.management/share/classes/module-info.java
OpenJ9 contributes `module-info.java.extra` for `java.management` which triggers use of `GenModuleInfoSource`, but that tool has not yet been updated to handle imports or annotations. Comment them out for now.
=> Comment out troublesome content in module-info.java

closed/GensrcJ9JCL.gmk, src/java.base/share/classes/java/util/Timer.java, src/java.base/share/classes/java/util/TimerTask.java
`TimerTask.nextExecutionTime` is added with `InternalCRIUSupport.getCheckpointRestoreTimeDelta()` to reflect the
elapsed time in milliseconds elapsed between Checkpoint and Restore;
Add `TimerTask.criuAdjustRequired` to determine if the `nextExecutionTime` is to be adjusted.
Cherry-pick https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/531
Depends on https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/459
=> CRIU update TimerTask.nextExecutionTime with checkpointRestoreTimeDelta

test/jdk/jni/nullCaller/CallHelper.hpp
Issue https://github.com/eclipse-openj9/openj9/issues/15168
Cherry pick https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/2 for openj9-openjdk-jdk
=> NullCallerTest clear exception before calling FindClass()

closed/src/java.base/share/classes/java/lang/ref/NativeReferenceQueue.java
Add stub implementation of NativeReferenceQueue
NativeReferenceQueue was added in openjdk to address usage of
j.u.c.locks with virtual threads. OpenJ9 doesn't have that problem as we
only use internal synchronization. As a result we can simply define the
type but make use of the super class methods.
Signed-off-by: Tobi Ajila <atobia@ca.ibm.com>
=> Add stub implementation of NativeReferenceQueue

closed/GensrcJ9JCL.gmk, make/modules/java.base/gensrc/GensrcCharsetMapping.gmk, src/java.base/share/classes/java/lang/ClassValue.java, src/java.base/share/classes/java/lang/invoke/ClassSpecializer.java, src/java.base/share/classes/java/util/concurrent/ConcurrentHashMap.java, src/java.base/share/classes/sun/nio/cs/StandardCharsets.java.template
Annotated `java.lang.ClassValue.initializeMap()`, `java.lang.invoke.ClassSpecializer.findSpecies()`, and `java.util.concurrent.ConcurrentHashMap.computeIfAbsent()` with `NotCheckpointSafe` to prevent `JVMCheckpointException`/deadlock;
Added `CRIU` `JPP` flag at `StandardCharsets.java.template`;
Modified `GensrcCharsetMapping.gmk` to run JPP after `StandardCharsets.java` generation.
Cherry-pick https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/128
=> Add NotCheckpointSafe annotations & JPP support for generated source

src/java.base/share/classes/java/util/Timer.java
The task could be null.
Cherry-pick https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/561
=> Add NULL check for CRIU field retrieval

test/jdk/java/lang/Class/GetPackageBootLoaderChildLayer.java
Port PR https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/557 from OpenJDK11 to OpenJDK Next.
In FIPS mode, the SecureRandom come from the provider SunPKCS11. So, add the module “jdk.crypto.cryptoki” into the test case, so that the test case can initialize the provider SunPKCS11 and get the SecureRandom from it in FIPS mode. This will make the test case works both in the FIPS and non-FIPS mode.
Signed-off-by: Tao Liu <tao.liu@ibm.com>
=> Update OpenJDK Next test case to add module jdk.crypto.cryptoki

src/java.base/share/classes/java/security/Security.java
If `loadedProps` is `false`, an exception will have been thrown; see
* 8155246: Throw error if default java.security file is missing
=> Remove redundant test of loadedProps

src/java.base/share/classes/java/lang/VirtualThread.java
The VirtualThread natives are needed to keep a list of every live virtual
thread for JVMTI. Since JVMTI agents can be attached at any time, enable
these natives by default.
Issue: eclipse-openj9/openj9#15183
Co-authored-by: Babneet Singh <sbabneet@ca.ibm.com>
Signed-off-by: Eric Yang <eric.yang@ibm.com>
=> Enable VirtualThread JVMTI natives by default

src/java.base/share/classes/jdk/internal/foreign/abi/aarch64/CallArranger.java, src/java.base/share/classes/jdk/internal/foreign/abi/s390x/sysv/CallArranger.java, src/java.base/share/classes/jdk/internal/foreign/abi/x64/sysv/CallArranger.java, src/java.base/share/classes/jdk/internal/foreign/abi/x64/windows/CallArranger.java, src/java.base/share/classes/jdk/internal/loader/NativeLibraries.java
The changes aim to enable the Linker's upcall handler to
support primitives and struct by replacing UpcallLinker
with the equivalent implemented in OpenJ9 on s390x,
Aarch64 and x86.
=> [JEP424] Enable FFI Upcall on s390x/Aarch64/x86 in JDKnext

closed/test/jtreg-ext/requires/OpenJ9PropsExt.java
Set following OpenJDK test properties to false:
```
vm.gc.G1
vm.gc.Parallel
vm.gc.Serial
vm.gc.Shenandoah
```
Cherrypick https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/29
closes https://github.com/eclipse-openj9/openj9/issues/15875
=> Set OpenJDK test properties to false in OpenJ9PropsExt

closed/custom/Main.gmk, make/Main.gmk
Cherry-pick ibmruntimes/openj9-openjdk-jdk19#30 for jdknext.
=> Enable building JVMTI serviceability tests

closed/autoconf/custom-spec.gmk.in
See also
* 8293965: Code signing warnings after JDK-8293550
=> Avoid warnings during code-signing on macOS

src/java.base/share/classes/java/lang/Thread.java
The method has a local variable called started as well.
=> In Thread.start(ThreadContainer) use this.started for clarity

test/hotspot/jtreg/serviceability/jvmti/events/VMObjectAlloc/vmobjalloc01/libvmobjalloc01.cpp
Fixes: https://github.com/eclipse-openj9/openj9/issues/15982
Related: https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/32
=> Fix JVMTI test: VMObjectAlloc/vmobjalloc01

src/java.base/share/classes/jdk/internal/foreign/abi/ppc64/TypeClass.java, src/java.base/share/classes/jdk/internal/foreign/abi/ppc64/aix/AixPPC64VaList.java, src/java.base/share/classes/jdk/internal/foreign/abi/ppc64/sysv/SysVPPC64leVaList.java, test/jdk/java/foreign/TestVarArgs.java, test/jdk/java/foreign/valist/VaListTest.java
The changes aim to enable the VaList support on Power
(Linux & AIX) by implementing the VaList specific APIs
in OpenJDK given the underlying code has been offered
in OpenJ9.
Note: 
The PR is part of FFI downcall & upcall work at
https://github.com/eclipse-openj9/openj9/issues/12412 and https://github.com/eclipse-openj9/openj9/issues/15068.
=> [JEP424] Implement VaList on Power (Linux & AIX) in JDKnext

closed/test/jtreg-ext/requires/OpenJ9PropsExt.java
`vm.cds` is set to `false` for `serviceability/jvmti/CanGenerateAllClassHook/CanGenerateAllClassHook.java` which is specific to hotspot sharedclass;
`vm.flagless` is set to `true` for `serviceability/jvmti/RedefineClasses/RedefineLeak.java` which OpenJ9 passes;
`vm.opt.final.ClassUnloading` is set to `false` for `serviceability/jvmti/RedefineClasses/RedefinePreviousVersions.java` which looks for a hotspot specific `Class unloading: has_previous_versions = false`.
Cherry-pick https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/34
closes https://github.com/eclipse-openj9/openj9/issues/16074
=> Add OpenJ9PropsExt properties for serviceability_jvmti_j9

closed/test/jtreg-ext/requires/OpenJ9PropsExt.java
The java/util/concurrent/ConcurrentHashMap/MapLoops.java test requires this property, along with -XX:+UseHeavyMonitors -XX:+VerifyHeavyMonitors options.
=> Set OpenJ9PropsExt.java vm.debug test property to false

src/java.base/share/classes/java/lang/Thread.java
Add extra check in getStackTrace0 under interruptLock to ensure only live thread is passed to native code.
Port of: https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/47
=> Fix Thread.getStackTrace synchronization

src/java.base/share/classes/java/lang/Thread.java
Set interrupt field before native call
There is a potential race if the interrupt field is set after the interrupt call where another thread may query interrupt status before the field is set.
Fixes: https://github.com/eclipse-openj9/openj9/issues/16174
Signed-off-by: Tobi Ajila <atobia@ca.ibm.com>
=> Set interrupt field before native call

src/java.base/share/classes/jdk/internal/foreign/PlatformLayouts.java, test/jdk/java/foreign/NativeTestHelper.java
The changes aim to restore the original alignment setting for long and pointer on AIX given the padding is required in native in the case of struct [int/float,long] and [int/float,pointer].
=> Fix the alignment issue with long & pointer on AIX

src/jdk.management.agent/share/conf/management.properties
OpenJ9 uses generic CompositeData, which uses Attribute to transmit data, rather than having custom CompositeData implementations.
Related to https://bugs.openjdk.org/browse/JDK-8283093 - JMX connections use an ObjectInputFilter by default
Closes https://github.com/eclipse-openj9/openj9/issues/16253
Tested the equivalent change via grinders
https://openj9-jenkins.osuosl.org/job/Grinder_testList_0/179/
https://openj9-jenkins.osuosl.org/job/Grinder_testList_0/180/
=> Add javax.management.Attribute to serialfilter

test/jdk/java/foreign/LibraryLookupTest.java, test/jdk/java/foreign/SafeFunctionAccessTest.java, test/jdk/java/foreign/StdLibTest.java, test/jdk/java/foreign/TestClassLoaderFindNative.java, test/jdk/java/foreign/TestDowncallScope.java, test/jdk/java/foreign/TestDowncallStack.java, test/jdk/java/foreign/TestFunctionDescriptor.java, test/jdk/java/foreign/TestHeapAlignment.java, test/jdk/java/foreign/TestMatrix.java, test/jdk/java/foreign/TestNULLAddress.java, test/jdk/java/foreign/TestNative.java, test/jdk/java/foreign/TestNulls.java, test/jdk/java/foreign/TestScopedOperations.java, test/jdk/java/foreign/TestSegments.java, test/jdk/java/foreign/TestStringEncoding.java, test/jdk/java/foreign/TestUpcallAsync.java, test/jdk/java/foreign/TestUpcallException.java, test/jdk/java/foreign/TestUpcallHighArity.java, test/jdk/java/foreign/TestUpcallScope.java, test/jdk/java/foreign/TestUpcallStack.java, test/jdk/java/foreign/TestUpcallStructScope.java, test/jdk/java/foreign/TestVarArgs.java, test/jdk/java/foreign/enablenativeaccess/TestEnableNativeAccess.java, test/jdk/java/foreign/handles/Driver.java, test/jdk/java/foreign/loaderLookup/TestLoaderLookup.java, test/jdk/java/foreign/loaderLookup/TestLoaderLookupJNI.java, test/jdk/java/foreign/malloc/TestMixedMallocFree.java, test/jdk/java/foreign/valist/VaListTest.java
The changes add Power & zLinux support to those FFI related jtreg test suites
to ensure they are executed on all supported platforms.
Note:
The PR is part of FFI downcall & upcall work at
eclipse-openj9/openj9#12412 and eclipse-openj9/openj9#15068.
=> Enable FFI related jtreg test suites on Power and zLinux

test/hotspot/jtreg/serviceability/jvmti/vthread/SelfSuspendDisablerTest/SelfSuspendDisablerTest.java
See https://github.com/eclipse-openj9/openj9/issues/16276#issuecomment-1310908446.
Port of https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/50.
Closes: https://github.com/eclipse-openj9/openj9/issues/16276.
=> Fix SelfSuspendDisablerTest

src/java.base/share/classes/java/lang/Thread.java
Fixes: https://github.com/eclipse-openj9/openj9/issues/15465 
Port of https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/51
Signed-off-by: Hang Shao <hangshao@ca.ibm.com>
=> Add synchronized block in getAndClearInterrupt()

src/java.base/share/classes/java/lang/Thread.java
At CRIU single threaded mode, returns `isInterruptedImpl()` for `isInterrupted()`, returns `interruptedImpl()` for `interrupted()`.
Cherry-pick https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/54/commits/c569e9e8668deb5e8a6f5b556c4912c834282611
=> Handle thread interrupted status at CRIU single threaded mode

src/java.base/share/classes/module-info.java, src/java.base/share/lib/security/default.policy, src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/P11Key.java, src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/SunPKCS11.java, src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/wrapper/PKCS11.java
Signed-off-by: Tao Liu <tao.liu@ibm.com>
This PR is a port from the PR https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/118 into JDKNext. And there are two differences between the JDK17 and JDKNext.
One is for the code about throw the PKCS11Exception, the PKCS11Exception class in JDKNext is changed by removing the “enum values set to variables” code, like below:
public static final long CKR_GENERAL_ERROR = RV.CKR_GENERAL_ERROR.value;
So, there is no way to get the errorCode by using the variable, like CKR_GENERAL_ERROR. Then the “throw new PKCS11Exception(CKR_GENERAL_ERROR);” have to be changed to “throw new PKCS11Exception(0x00000005L, null);”, by using the long errorCode directly.
Another one is in the P11Key class, in the method “static PrivateKey privateKey()”. Before JDKnext, …
=> Support export/import of cryptographic keys in FIPS Mode

test/hotspot/jtreg/serviceability/jvmti/vthread/BreakpointInYieldTest/libBreakpointInYieldTest.cpp, test/hotspot/jtreg/serviceability/jvmti/vthread/MethodExitTest/libMethodExitTest.cpp, test/hotspot/jtreg/serviceability/jvmti/vthread/NullAsCurrentThreadTest/libNullAsCurrentThreadTest.cpp, test/hotspot/jtreg/serviceability/jvmti/vthread/VThreadTest/libVThreadTest.cpp, test/hotspot/jtreg/serviceability/jvmti/vthread/VThreadUnsupportedTest/libVThreadUnsupportedTest.cpp, test/lib/jdk/test/lib/jvmti/jvmti_common.h
Currently, extension event numbers are hard-coded in the tests. This is
invalid since the extension event numbers can vary between
implementations. Instead, GetExtensionEvents should be used to derive
the extension event numbers.
Related: https://github.com/eclipse-openj9/openj9/pull/16501
Related: https://github.com/eclipse-openj9/openj9/issues/16167
=> Use GetExtensionEvents to derive extension event numbers

src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/Config.java
Updating tokenLabel check so keyword is recorded properly.
Signed-off-by: Bob Du bob.du@ibm.com
=> tokenLabel duplicate entry fix

test/jdk/java/lang/Thread/virtual/HoldsLock.java
- Ensure only live threads are being checked
Port of https://github.com/ibmruntimes/openj9-openjdk-jdk19/pull/71
=> Add null check for virtual thread HoldsLock test

closed/src/java.base/aix/native/libsyslookup/syslookup.c, src/java.base/share/classes/jdk/internal/foreign/SystemLookup.java
The changes aim to support the symbol lookup via FFI for
the missing libc functions in loading the default library on
AIX by inlining their address into a function list in native to
ensure they are correctly invoked with the native address
fetched in the FFI code.
Signed-off-by: ChengJin01 [jincheng@ca.ibm.com](mailto:jincheng@ca.ibm.com)
=> [FFI]Inline the missing libc functions for symbol lookup on AIX

src/java.base/share/classes/java/security/Security.java
When making use of the CRIU feature for a fast startup it has been found
that fetching algorithms is quite slow from the providers installed.
This update saves all algorithms available in all providers prior to
a checkpoint being taken. This cache then becomes available for callers
after a restore has taken place.
Any updates to the security providers order made via the Security
classes triggers the invalidation of this cache.
This update is dependent upon https://github.com/eclipse-openj9/openj9/pull/16888
Signed-off-by: Jason Katonica <katonica@us.ibm.com>
=> Cache Security Algorithms For CRIU Startup

src/java.base/share/classes/jdk/internal/foreign/CABI.java, src/java.base/share/classes/jdk/internal/foreign/PlatformLayouts.java, src/java.base/share/classes/jdk/internal/foreign/SystemLookup.java, src/java.base/share/classes/jdk/internal/foreign/abi/SharedUtils.java, src/java.base/share/classes/jdk/internal/foreign/abi/aarch64/CallArranger.java, src/java.base/share/classes/jdk/internal/foreign/abi/aarch64/windows/WindowsAArch64VaList.java, src/java.base/share/classes/jdk/internal/foreign/abi/ppc64/aix/AixPPC64Linker.java, src/java.base/share/classes/jdk/internal/foreign/abi/ppc64/aix/AixPPC64VaList.java, src/java.base/share/classes/jdk/internal/foreign/abi/ppc64/aix/CallArranger.java, src/java.base/share/classes/jdk/internal/foreign/abi/ppc64/sysv/CallArranger.java, src/java.base/share/classes/jdk/internal/foreign/abi/ppc64/sysv/SysVPPC64leLinker.java, src/java.base/share/classes/jdk/internal/foreign/abi/ppc64/sysv/SysVPPC64leVaList.java, src/java.base/share/classes/jdk/internal/foreign/abi/s390x/sysv/CallArranger.java, src/java.base/share/classes/jdk/internal/foreign/abi/s390x/sysv/SysVS390xLinker.java, src/java.base/share/classes/jdk/internal/foreign/abi/s390x/sysv/SysVS390xVaList.java, src/java.base/share/classes/jdk/internal/foreign/abi/x64/sysv/CallArranger.java, src/java.base/share/classes/jdk/internal/foreign/abi/x64/windows/CallArranger.java, src/java.base/share/classes/jdk/internal/foreign/layout/ValueLayouts.java
The changes update part of our code in the FFI framework
against the latest APIs specified in JDKnext to accommodate
the new features of JEP434.
Note:
This is the part of implementation intended for
#eclipse-openj9/openj9/issues/16329
=> Update the FFI related code intended for JEP434

src/java.base/share/classes/jdk/internal/foreign/abi/AbstractLinker.java
This interface is defined by:
b4a1996aa9df668657832975eb12ef1b9411dfd7 8303684: Lift upcall sharing mechanism to AbstractLinker (mainline)
That change is part of #572 which we cannot merge into the openj9 branch because of https://github.com/eclipse-openj9/openj9/issues/16936, however it will allow https://github.com/eclipse-openj9/openj9/pull/16985 to be merged while allowing the openj9 branch to continue to build with the head of the openj9 repository.
=> Add preview of AbstractLinker.UpcallStubFactory

src/java.base/share/classes/jdk/internal/foreign/abi/aarch64/CallArranger.java, src/java.base/share/classes/jdk/internal/foreign/abi/ppc64/aix/CallArranger.java, src/java.base/share/classes/jdk/internal/foreign/abi/ppc64/sysv/CallArranger.java, src/java.base/share/classes/jdk/internal/foreign/abi/s390x/sysv/CallArranger.java, src/java.base/share/classes/jdk/internal/foreign/abi/x64/sysv/CallArranger.java, src/java.base/share/classes/jdk/internal/foreign/abi/x64/windows/CallArranger.java
The minor changes wrap up the existing upcall specific code
in `CallArranger.arrangeUpcall()` with `UpcallStubFactory`
introduced in JDK20 by invoking `UpcallLinker.makeFactory()`
implemented in OpenJ9.
=> [FFI/JDK21] Update the code against the changes in OpenJDK

closed/custom/modules/java.base/Copy.gmk
Recognize `OpenJ9` flags in `openjdk` `jcl` natives
Copied `j9cfg.h` & `omrcfg.h` into `$(SUPPORT_OUTPUTDIR)/modules_include/java.base`.
related https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/591
=> Recognize OpenJ9 flags in openjdk jcl natives

closed/OpenJ9.gmk, closed/autoconf/custom-spec.gmk.in, closed/custom/Main.gmk, closed/custom/modules/java.base/Copy.gmk
OpenJDK JCL natives include openj9 config header files
Created `openj9_config_header_rules` and `target openj9-config-headers` which is invoked after `build-j9`, and copy `j9cfg.h` & `omrcfg.h` into `$(SUPPORT_OUTPUTDIR)/openj9_include`;
Added `-I$(SUPPORT_OUTPUTDIR)/openj9_include` for OpenJDK natives.
related
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/592
=> OpenJDK JCL natives include openj9 config header files

make/conf/version-numbers.conf
Neither java 18 nor 19 are acceptable for the boot JDK.
See https://github.com/eclipse-openj9/openj9/issues/17289.
=> Revert version-numbers.conf

test/jdk/java/lang/Thread/virtual/Collectable.java
See the below comments for the justification to run the Collectable
test with `-Xjit:enableAggressiveLiveness`:
- https://github.com/eclipse-openj9/openj9/issues/17241#issuecomment-1551841207
- https://github.com/eclipse-openj9/openj9/issues/8897#issuecomment-607897793
Related: eclipse-openj9/openj9#17241
=> Run the Collectable test w/ -Xjit:enableAggressiveLiveness

test/jdk/java/foreign/TestClassLoaderFindNative.java
The change is to restore the previous fix in OpenJDK
to deal with the native memory access given 
SymbolLookup.loaderLookup().find() returns a zero-sized
segment for ADDRESS as explained in OpenJDK, in which
case it should be reinterpreted as an valid segment
with the specified size to ensure it works correctly.
=> [FFI/Jtreg_JDKnext] Fix the native segment access in test

test/jdk/java/foreign/TestVarArgs.java
The change is to remove the previous fix of promoting
the float to double on AIX in TestVarArgs.java given
the related code in OpenJDK was updated in which case
the fix is no longer required on AIX.
=> [FFI/Jtreg_JDKnext] Remove the promotion code for double on AIX

test/jdk/java/foreign/TestLayouts.java
The change distinguishes the LE/BE platforms by checking
the case of symbol for JAVA_INT.
=> [FFI/Jtreg_JDKnext] Identify the case of symbol for JAVA_INT

closed/src/java.base/share/classes/openj9/internal/security/RestrictedSecurity.java, src/java.base/share/classes/java/security/Provider.java
Signed-off-by: Tao Liu <tao.liu@ibm.com>
This PR is for adding the services check in Provider legacy "put()" method and debug info in Java Security Restricted Mode.
The legacy “put()” method is for adding the services and it is used by provider SUN and SunEC in Semeru OpenJDK8. From OpenJDK11 and above versions, all those usages of “put()” method changed to "putService()" method. But we still need to check the services which are added by the legacy “put()” method in Java Security Restricted Mode. So, updated the codes for checking the registered services, only allowed the needed services be stored in the "legacyMap".
=> Add checks in Provider put() method in Java Security Restricted Mode

closed/test/jtreg-ext/requires/OpenJ9PropsExt.java
Add `OpenJ9PropsExt` properties for `vm.gc.ZGenerational` & `vm.gc.ZSinglegen`
This addresses the error from [an internal JDK21 build](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_extended.openjdk_ppc64_aix_Personal/1/consoleFull)
```
09:33:43  TEST: jdk/dynalink/TypeConverterFactoryMemoryLeakTest.java#with_ZGC_Generational
09:33:43  
09:33:43  TEST RESULT: Error. Error evaluating expression: invalid boolean value: `null' for expression `vm.gc.ZGenerational'
09:33:43  --------------------------------------------------
09:33:43  TEST: jdk/dynalink/TypeConverterFactoryMemoryLeakTest.java#with_ZGC_Singlegen
09:33:43  
09:33:43  TEST RESULT: Error. Error evaluating expression: invalid boolean value: `null' for expression `vm.gc.ZSinglegen'
```
Signed-off-by: Jason Feng …
=> Add OpenJ9PropsExt properties for vm.gc.ZGenerational & vm.gc.ZSinglegen

make/Main.gmk
Building `java.base.jmod` requires all non-upgradable modules, but the macro `FindAllUpgradeableModules` doesn't take into account requires relationships.
Fixes: https://github.com/eclipse-openj9/openj9/issues/17757.
=> Revert: 8310379: Relax prerequisites for java.base-jmod target

closed/custom/modules/java.base/Copy.gmk, closed/src/java.base/aix/native/libjncrypto/NativeCrypto_md.c
Additional options for potential library files are added to accommodate to OpenSSL 3.x.
The list of potential library files to be bundled with OpenJDK is, also, altered to allow bundling of OpenSSL 3.x while avoiding conflict with other applications that might be using earlier versions.
=> Allow loading of OpenSSL 3.x native library for AIX

test/jdk/java/foreign/trivial/TestTrivialUpcall.java
The tiny change is to capture the error message from `System.err`
rather than `System.out` to support the related code in OpenJ9
at #eclipse-openj9/openj9/pull/17847 which is different from the RI
implementation.
=> [FFI/Jtreg_JDKnext] Capture the invalid thread state in upcall

test/hotspot/jtreg/serviceability/jvmti/vthread/BoundVThreadTest/libBoundVThreadTest.cpp
After GetAllStackTraces, derive the thread object from the
stack_info array, which is filled by GetAllStackTraces.
Currently, the thread object is retrieved from the threads_ptr
array, which is filled by GetAllThreads before the call to
GetAllStackTraces. Live platform threads might have been created
or destroyed between the call to GetAllThreads and GetAllStackTraces.
This makes the threads_ptr array stale after GetAllStackTraces. A bad
thread object is accessed from the stale threads_ptr which causes a
segfault.
Port of https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/25.
Related: https://github.com/eclipse-openj9/openj9/issues/17868
Signed-off-by: Babneet Singh [sbabneet@ca.ibm.com](mailto:sbabneet@ca.ibm.com)
=> Fix BoundVThreadTest - Bad Thread Object

src/java.base/share/classes/sun/security/ec/SunEC.java
See https://github.com/eclipse-openj9/openj9/issues/18071.
Also, some tests with non-standard `java.policy` fail otherwise:
```
Caused by: java.security.AccessControlException: Access denied ("java.util.PropertyPermission" "os.name" "read")
at java.base/java.security.AccessController.throwACE(AccessController.java:177)
at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:239)
at java.base/java.security.AccessController.checkPermission(AccessController.java:386)
at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:411)
at java.base/java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1146)
at java.base/java.lang.System.getProperty(System.java:663)
at java.base/java.lang.System.getProperty(System.java:646)
at …
```
=> Assert privilege accessing os.name

test/hotspot/jtreg/serviceability/jvmti/vthread/VThreadEventTest/libVThreadEventTest.cpp
A change similar to https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/545 is needed for this new test source file.
Note: This targets the openj9-staging branch.
=> Use GetExtensionEvents() to derive JVMTI extension event numbers

src/java.base/unix/native/libjli/java_md.c
Related to https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/664
=> Fix variable names for parsing -XX:[+/-]UseZlibNX on AIX

closed/make/modules/openj9.dtfj/Launcher.gmk
It would conflict with the anticipated tool from openjdk.
Issue: https://github.com/eclipse-openj9/openj9/issues/18193.
=> Stop creating jextract launcher

closed/src/java.base/share/classes/com/sun/crypto/provider/NativeChaCha20Cipher.java
The expected behaviour for reuse of `NativeChaCha20Cipher` for decryption is altered to match the existing Sun implementation in `ChaCha20Cipher`, as updated in OpenJDK21.
The following scenarios are now allowed for decryption:
- Reinitialize with same key + nonce
- Update `AAD` after a successful `doFinal()` without reinitializing
- Update `AAD` after an `AEADBadTagException`
Those scenarios are not allowed (i.e., an exception is thrown) in OpenJDK20 and earlier.
This fix addresses the failures mentioned in issue https://github.com/eclipse-openj9/openj9/issues/17632
=> Allow ChaCha20 cipher reuse with same key/IV or without init after decryption

closed/src/java.base/share/classes/sun/security/ec/NativeECKeyPairGenerator.java
At the moment, if there is an OpenSSL failure when using `NativeECKeyPairGenerator`, a flag for that particular curve is set and the Sun Java implementation is used to complete the task. 
If another instance of `NativeECKeyPairGenerator` reaches the same failure, a `ProviderException` is thrown, as the issue with that particular curve should have been discovered during the call to `initialize()` thus creating and using an instance of `ECKeyPairGenerator`, and that particular point should never have been reached.
However, in the scenario where the second instance of `NativeECKeyPairGenerator` has been initialized earlier, the flag for the problematic curve will never be discovered.
This fix ensures that we always revert to the Sun Java implementation when an OpenSSL failure occurs. …
=> Always revert to Java impl when OpenSSL fails

test/jdk/com/sun/tools/attach/warnings/Application.java, test/jdk/com/sun/tools/attach/warnings/DynamicLoadWarningTest.java
Ensure `AttachAPI` initialized before starting attaching tests
Check `AttachHandler.isAttachApiInitialized()`, and delay to allow `AttachAPI` initialization if necessary. 
related https://github.com/eclipse-openj9/openj9/issues/18125
=> Ensure AttachAPI initialized before starting attaching tests

test/jdk/java/lang/Thread/virtual/stress/Skynet.java
Skynet is a stress benchmark, which exceeds the below 4G capacity
of `-Xcompressedrefs`. The current workaround is to use
`-Xnocompressedrefs` where memory can be allocated outside the 4G
boundary. 
To run Skynet with `-Xcompressedrefs`, the following features will be
needed:
- Move unmounted continuation stacks out of the low memory area.
- Improve performance of the sub-4G allocator so that it doesn't
regress under high memory usage.
Depends on eclipse-openj9/openj9#18251
Related: eclipse-openj9/openj9#16728
Related: eclipse-openj9/openj9#15781
=> Run virtual/stress/Skynet with -Xnocompressedrefs

test/jdk/java/foreign/nested/TestNested.java
The changes reflect the actual padding bytes of
the failing test structs support double on AIX.
Related: #eclipse-openj9/openj9/issues/18287
=> [FFI/Jtreg_JDKnext] Adjust the padding bytes of struct on AIX

closed/OpenJ9.gmk, closed/get_j9_source.sh, make/autoconf/jdk-options.m4
On some platforms, the date utility doesn't support the "%s" format specifier or supports neither the "-f" option nor the "-j" option. Use the boot jdk to run a java program instead.
=> Replace date utility usage with DateUtil for SOURCE_DATE

test/hotspot/jtreg/serviceability/jvmti/vthread/ThreadListStackTracesTest/ThreadListStackTracesTest.java
Adjust ThreadListStackTracesTest for checkReentrantLock
to be ready when the virtual thread state is WAITING after
the reentrant lock parks the virtual thread. When the
virtual thread is mounted, the virtual thread state, which
is obtained from the carrier thread, can transition
between WAITING and RUNNABLE before the virtual thread is
parked on the lock.
Issue: https://github.com/eclipse-openj9/openj9/issues/18089
Signed-off-by: Amarpreet Singh <Amarpreet.A.Singh@ibm.com>
=> Adjust ThreadListStackTracesTest for checkReentrantLock

src/java.base/share/classes/java/io/PrintStream.java
`CRIU` adds `@NotCheckpointSafe` for `PrintStream.writeln(String)`
related
* https://github.com/eclipse-openj9/openj9/issues/18471
=> CRIU adds @NotCheckpointSafe for PrintStream.writeln(String)

closed/GensrcJ9JCL.gmk
Add `PrintStream.java` to `$(SUPPORT_OUTPUTDIR)/overlay`
Otherwise, the non-Linux platform won't build.
related 
* https://github.com/eclipse-openj9/openj9/issues/18471
FYI @tajila 
=> Add PrintStream.java to $(SUPPORT_OUTPUTDIR)/overlay

src/jdk.compiler/share/classes/com/sun/tools/javac/comp/TransLiterals.java
At least temporarily until a newer boot JDK can be used.
Fixes: https://github.com/eclipse-openj9/openj9/issues/18486.
=> Avoid Java 21 source features

closed/GensrcJ9JCL.gmk, src/java.base/share/classes/jdk/internal/ref/PhantomCleanable.java
Add NotCheckpointSafe annotations to PhantomCleanable to 
avoid blocking operations during restore in CRIU single 
thread mode, and fix the failures in the
cmdLineTester_criu_nonPortableRestore tests that occur 
due to blocking operations during restore in CRIU
single thread mode.
Issue: eclipse-openj9/openj9#18399
Signed-off-by: Amarpreet Singh <Amarpreet.A.Singh@ibm.com>
=> Add NotCheckpointSafe annotations to PhantomCleanable

test/jdk/java/foreign/security.policy
The change ensure the system property required in OpenJ9
is permitted during the class initialization when the
test suite is executed.
Fixes: #eclipse-openj9/openj9/issues/18507
=> [FFI/Jtreg_JDK22] Add permission for os.arch in the security policy

src/java.base/share/classes/java/lang/Thread.java
The current implementation contains some code from the j9 threading implementation. With openjdk threading we dont need a deadinterrupt (which the old code is attempting to simulate) field as the interrupt state is tracked in the JCL rather than the JVM.
Also, the old code actually clears the interrupt state which is incorrect.
=> Remove unnecessary interrupt

closed/src/java.base/share/classes/sun/security/ec/NativeECKeyPairGenerator.java, closed/src/java.base/share/classes/sun/security/ec/NativeXDHKeyPairGenerator.java
If one initializes any of the `NativeECKeyPairGenerator` or `NativeXDHKeyPairGenerator` with a `SecureRandom` implementation, it is effectively ignored, as the equivalent OpenSSL code is used instead.
This fix changes that to using OpenSSL only when no or the default Sun implementation of `SecureRandom` is provided. In any other case, the original Java implementation is used to generate the appropriate `KeyPair`.
Signed-off by: Kostas Tsiounis kostas.tsiounis@ibm.com
=> Revert to Java impl when non-default SecureRandom present

make/Main.gmk
Some of them, such as jfr, don't build.
Issue https://github.com/eclipse-openj9/openj9/issues/18618
Tested via https://openj9-jenkins.osuosl.org/job/Build_JDKnext_aarch64_mac_OpenJDK/216/
Note this is merging to openj9-staging which will automatically launch an Acceptance build.
=> Avoid building test jars in the test image

src/jdk.javadoc/share/classes/jdk/javadoc/internal/tool/Start.java
Temporary workaround for https://github.com/eclipse-openj9/openj9/issues/18707.
=> Allow JDK 20 for boot jdk

make/autoconf/lib-freetype.m4
Bundles freetype on Linux.
See https://github.com/adoptium/temurin-build/pull/3557
=> Bundle freetype by default to match Semeru builds

src/java.base/share/classes/java/lang/Thread.java, src/java.base/share/classes/java/lang/ThreadGroup.java
Until https://github.com/eclipse-openj9/openj9/issues/18758 can be addressed, this restores referenced API in `Thread` and `ThreadGroup`, by partially reverting
* 8320532: Remove Thread/ThreadGroup suspend/resume
* 8320786: Remove ThreadGroup.stop
=> Temporarily restore Thread/ThreadGroup suspend/resume/stop

src/java.base/share/classes/java/lang/Thread.java
It was removed in #746, but should not have been. The consequences were seen in ibmruntimes/openj9-openjdk-jdk21#133 which sought to remove the same synchronization.
=> Restore required synchronization in Thread.getAndClearInterrupt()

closed/OpenJ9.gmk, closed/autoconf/custom-hook.m4, closed/autoconf/custom-spec.gmk.in, closed/autoconf/toolchain.cmake.in
On Windows, the library creation utility is now captured in `$(LIB)` instead of `$(AR)`. Define `OPENJ9_VS_LIB` instead of `LIB` (to be exported as `LIB` where needed).
Fixes: https://github.com/eclipse-openj9/openj9/issues/19049.
=> Adapt to recent build changes for Windows

test/jdk/java/foreign/nested/libNested.c, test/jdk/java/foreign/shared.h
The intention of the changes is to avoid conflicts
with our own code with 4-byte alignment for double on
AIX which already supports both the default setting
by the compiler and the natural alignment for double.
=> [FFI/JTreg] Remove the pragma lines for AIX in test suites

.gitignore
Affected by upstream change:
* [8326964: Remove Eclipse Shared Workspaces](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/66c80c80d2e0b1d64a77b8bed644c8c3f7506719)
=> Fix .gitignore entry for .project

test/jdk/ProblemList-FIPS140_2.txt
- exclude FIPS test in JDK23 to match JDK22/JDK21
related:https://github.ibm.com/runtimes/backlog/issues/1397
=> Update FIPS test exclude file for JDK23

closed/src/java.base/share/classes/jdk/crypto/jniprovider/NativeCrypto.java, closed/src/java.base/share/classes/sun/security/provider/NativeMD5.java, closed/src/java.base/share/native/libjncrypto/NativeCrypto.c, src/java.base/share/classes/sun/security/provider/SunEntries.java
A new class, namely `MD5.java`, is created and the corresponding options are added in other places to allow for the use of native `OpenSSL` library to perform `MD5` digests.
=> Add support for MD5 digest using native OpenSSL library

test/jdk/java/lang/String/CompactString/MaxSizeUTF16String.java
Openj9 can allocate `new byte[Integer.MAX_VALUE - 1]` but this exceeds the Hotspot implementation limit.
Fixes https://github.com/eclipse-openj9/openj9/issues/19303
Tested in grinder https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/3472 showing `MaxSizeUTF16String::testMaxUTF8_UTF16Encode` is SUCCESSFUL. There is another issue https://github.com/eclipse-openj9/openj9/issues/19309 preventing the test from passing.
=> Fix MaxSizeUTF16String test to support OpenJ9

doc/building.html, doc/building.md, make/autoconf/build-performance.m4, make/autoconf/flags-cflags.m4, make/autoconf/flags-ldflags.m4, make/autoconf/flags.m4, make/autoconf/spec.gmk.template, make/autoconf/toolchain.m4, make/common/native/Link.gmk, make/common/native/Paths.gmk, make/hotspot/lib/CompileJvm.gmk, make/modules/java.base/Lib.gmk, make/modules/java.base/lib/CoreLibraries.gmk, make/modules/java.desktop/lib/Awt2dLibraries.gmk, make/test/JtregNativeJdk.gmk
Revert ["8327701: Remove the xlc toolchain"](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/ceeb8571963012d55755ad7d875b5fedb93e7db1).
=> Fix compile issues with xlc on AIX

closed/CopySupport.gmk, closed/OpenJ9.gmk, closed/custom/modules/java.base/Copy.gmk, closed/make/modules/ibm.healthcenter/Copy.gmk, closed/src/java.base/share/classes/openj9/internal/security/RestrictedSecurity.java, src/java.base/share/classes/java/security/Security.java
They were removed by:
* [8330351: Remove the SHARED_LIBRARY and STATIC_LIBRARY macros](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/51bae6ee3f3f889b19d2f703709d71de31d4154a)
Fixes: https://github.com/eclipse-openj9/openj9/issues/19330.
=> Remove uses of SHARED_LIBRARY and STATIC_LIBRARY

buildenv/jenkins/jobs/infrastructure/copyrightCheckDir.groovy
Tested (a version modified to fail) via https://openj9-jenkins.osuosl.org/view/Infrastructure/job/CopyrightCheck-OpenJDK22/137/
The expected Slack message occurred.
https://openj9.slack.com/archives/CBRG8KTGV/p1713474395613149
Used https://github.com/eclipse-openj9/openj9/blob/master/buildenv/jenkins/jobs/infrastructure/artifactory_cleanup.groovy#L76 as an example.
=> Update copyrightCheckDir to post to Slack on failure

closed/src/java.base/share/classes/jdk/crypto/jniprovider/NativeCrypto.java, closed/src/java.base/share/classes/sun/security/ec/NativeECDSASignature.java, closed/src/java.base/share/native/libjncrypto/NativeCrypto.c, src/java.base/share/classes/sun/security/ec/SunEC.java
A new class, namely `NativeECDSASignature.java`, is created and the corresponding options are added in other places to allow for the use of native `OpenSSL` library to create and verify `ECDSA` signatures.
=> Add support for ECDSA signatures using native OpenSSL library

closed/src/java.base/share/classes/sun/security/ec/NativeECDHKeyAgreement.java
There are additional checks that are required during the `init` and `doPhase` parts of `ECDH` key agreement. Those checks are already present in the original `ECDHKeyAgreement` class, so they had to be added to the `NativeECDHKeyAgreement` class as well.
Both the private and public key are, also, set to null at the beginning of the initialization, regardless of the method's outcome, meaning that in case of failure the previous keys cannot be used. This is new in JDK23.
Fixes: https://github.com/eclipse-openj9/openj9/issues/19437
=> Add additional checks to NativeECDHKeyAgreement to match upstream

closed/src/java.base/share/classes/sun/security/ec/NativeECDHKeyAgreement.java
Noticed while reviewing https://github.com/ibmruntimes/openj9-openjdk-jdk22/pull/58.
=> Remove unused imports

closed/src/java.base/share/classes/sun/security/ec/NativeECDHKeyAgreement.java, closed/src/java.base/share/classes/sun/security/ec/NativeECDSASignature.java, closed/src/java.base/share/classes/sun/security/ec/NativeECUtil.java, src/java.base/share/classes/sun/security/ec/ECPrivateKeyImpl.java, src/java.base/share/classes/sun/security/ec/ECPublicKeyImpl.java
The acquisition of a native pointer for an EC key, private or public, is being moved to the `ECUtil`, instead of the implementation classes of said keys. This allows use of interop keys, rather than just keys coming from `SunEC`.
The methods to get the pointers to the native keys are called during the initialization phases, to discover the possibility of not being able to utilize the native code and revert to the Java implementation early.
The `engineUpdate()` methods of the `RawECDSA` subclass are, also, updated to use the java implementation, if one has been initialized.
=> Move getting native pointer to ECUtils and acquire during init

src/java.base/share/classes/sun/security/ec/ECPrivateKeyImpl.java, src/java.base/share/classes/sun/security/ec/ECPublicKeyImpl.java
There is no need for additional code in the `ECPrivateKeyImpl` and `ECPublicKeyImpl` classes anymore, compared to the upstream, so the IBM copyright is also no longer needed.
Signed-off by: Kostas Tsiounis <kostas.tsiounis@ibm.com>
=> Remove unnecessary changes to EC key implementations

.copyrightignore, buildenv/jenkins/jobs/infrastructure/copyrightCheck
The `.copyrightignore` file in each of the extension repositories contains some comments attempting to describe how patterns are interpreted. Those comments and the actual behavior of the groovy script are not consistent. See the console log of https://openj9-jenkins.osuosl.org/job/PullRequest-CopyrightCheck-OpenJDK11/1001 for a recent example.
The table below shows a few patterns from jdk11, showing for each the derived regular expression and problems for that entry.
| Pattern | Resulting Regular Expression | Comments |
|:---|:---|:---|
| src/bsd/doc | src/+bsd/+doc.\* | no need to use `+` |
| src/jdk.crypto.ec/share/native/libsunec/impl | src/+jdk.crypto\\.ec/+share/+native/+libsunec/+impl | first `.` should be escaped, `.\*` suffix is missing |
| /test | test/.\*\|$ | unwanted `\|`, …
=> Fix mapping of .copyrightignore patterns to regular expressions

closed/src/java.base/share/classes/sun/security/ec/NativeECDHKeyAgreement.java, closed/src/java.base/share/classes/sun/security/ec/NativeECDSASignature.java, closed/src/java.base/share/classes/sun/security/ec/NativeECKeyPairGenerator.java, closed/src/java.base/share/classes/sun/security/ec/NativeECUtil.java, src/java.base/share/classes/sun/security/ec/SunEC.java, src/java.base/share/classes/sun/security/ssl/NamedGroup.java, src/java.base/share/classes/sun/security/ssl/SignatureScheme.java, test/jdk/javax/net/ssl/TLSCommon/TLSTest.java, test/jdk/javax/net/ssl/TLSv13/ClientHelloKeyShares.java, test/jdk/sun/security/pkcs11/ec/TestECDSA.java
This update supports both the `ecdsa_brainpoolP512r1tls13_sha512`
signature scheme and `brainpoolP512r1tls13` key exchange mechanisms
defined in `RFC 8734` using `openssl`.
The `NativeECDHKeyAgreement` class was enhanced to allow for a key
exchange to take place using the EC named curve `brainpoolP512r1`. This
functionality can be enabled by configuring the named group
`brainpoolP512r1tls13`.
The `NativeECDSASignature` class was enhanced to allow for `ECDSA`
`brainpoolP512r1` signatures to be routed to openssl for execution.
The `NativeECKeyPairGenerator` was enhanced to allow for
`brainpoolP512r1` based keys to be generated with openssl.
Both the `ecdsa_brainpoolP512r1tls13_sha512` signature scheme and
`brainpoolP512r1tls13` key exchange mechanism are optionally configured
and not …
=> Support brainpoolP512r1 TLS 1.3 RFC 8734

src/java.base/share/classes/java/lang/Thread.java, src/java.base/share/classes/java/lang/ThreadGroup.java
- Revert "Temporarily restore Thread/ThreadGroup suspend/resume/stop", https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/729 
Related Issue: https://github.com/eclipse-openj9/openj9/issues/18758
=> Revert "Temporarily restore Thread/ThreadGroup suspend/resume/stop" (#729)

src/java.base/share/classes/jdk/internal/javac/PreviewFeature.java
To allow continued use of a Java 21 bootjdk (see https://github.com/eclipse-openj9/openj9/issues/19994).
=> Temporarily restore PreviewFeature.Feature.UNNAMED_CLASSES

src/java.base/share/classes/jdk/internal/util/OperatingSystem.java, src/java.base/share/classes/jdk/internal/util/PlatformProps.java.template
Builds for z/TPF are done via cross-compilation.
When using the BOOT_JDK (s390x linux) the JLINK tool validates the OS it's building for.
The proposed update simply adds z/TPF as a recognized Operating System for Semeru.
If accepted looking to get this into JDK 21 Releases/Refreshes.  Please let me know what the earliest release this would be available in, and if it's possible to get the update into in-progress refreshes for Semeru 21.
=> z/TPF: Add z/TPF as a recognized operating system

closed/autoconf/custom-spec.gmk.in
CMAKE is defined in `spec.gmk` since
* [8329816: Add SLEEF version 3.6.1](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/63237415e7f4cc5b8ea27fa379a9b2ae167021c8)
=> Remove redundant definition of CMAKE

src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/SunPKCS11.java
In Java 8 with IBMPKCS11Impl, we allowed the usage of `1.2.840.10045.2.1` as an alias for `EC` when using ECKeyFactory. This is support we want to continue to offer with SunPKCS11 and Semeru.
Changing the function from `d()` to [`dA()`](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/openj9/src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/SunPKCS11.java#L726) allows [`getAliases()`](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/12ee8ca858929b069c1635152a1fefdf778e9af1/src/java.base/share/classes/sun/security/util/SecurityProviderConstants.java#L81) to be called. which checks the [list of known aliases](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/12ee8ca858929b069c1635152a1fefdf778e9af1/src/java.base/share/classes/sun/security/util/KnownOIDs.java#L281) …
=> Add support for EC aliases in SunPKCS11

test/jdk/java/lang/ClassLoader/nativeLibrary/NativeLibraryTest.java
Hold the `testLoader` reference to prevent GC
The GC might occur before the second native library loading by another class loader, hold the first `testLoader` reference to prevent GC, and ensure `UnsatisfiedLinkError`.
Related to
* https://github.com/eclipse-openj9/openj9/pull/20265
=> Hold the testLoader reference to prevent GC

test/jdk/java/foreign/StdLibTest.java
When making a downcall to standard printf function, use a memorysegment allocated with native charset for strings.
=> Use native encoded bytes when making a downcall to standard printf 

closed/test/jtreg-ext/requires/OpenJ9PropsExt.java
Mirroring the upstream change:
* [8341138: Rename jtreg property docker.support as container.support](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/8bec8a05c2b44ccdfce9746608cc9aef736ae4a9)
=> Rename jtreg property docker.support as container.support

src/java.base/share/classes/jdk/internal/javac/PreviewFeature.java
Temporarily restore `PreviewFeature.Feature.FOREIGN` & `STRING_TEMPLATES`
To allow a Java 21 bootjdk.
Issue https://github.com/eclipse-openj9/openj9/issues/20402
=> Temporarily restore PreviewFeature.Feature.FOREIGN & STRING_TEMPLATES

src/java.base/share/classes/sun/security/ec/SunEC.java
The parameter used to indicate the name of the algorithm, whose native implementation's availability is being checked, was incorrectly set to the provider name, leading to incorrect debug trace messages.
=> Fix names of algorithms printed in debug trace

closed/src/java.base/share/classes/openj9/internal/security/RestrictedSecurity.java
In Restricted Security Mode, add the error message when the profile name is used without the version part in "-Dsemeru.customprofile=", and the specified profile does not exist in the java.security file.
=> Add error message when the profile does not exist

src/java.base/share/classes/java/lang/Thread.java
`ThreadGroup.checkAccess()` is final and empty. Related to upstream changes in
- [8343981: Remove usage of security manager from Thread and related classes](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/3fc32e5bf9649969ee3a156efc9c64b760cf889e)
Also remove unused import.
=> Remove useless call to ThreadGroup.checkAccess()

closed/make/modules/openjceplus/Copy.gmk, closed/make/modules/openjceplus/Lib.gmk
OpenJCEPlus providers are supported on the Mac OS with aarch64 and amd64 architectures. This PR aims to add aarch64-mac and x86_64-mac to platforms bundling OpenJCEPlus.
=> Enable aarch64/x86-64 Mac bundling OpenJCEPlus

closed/make/modules/openjceplus/Lib.gmk
Non-FIPS OpenJCEPlus provider is supported on the Linux aarch64. This PR aims to add aarch64-linux to platform bundling OpenJCEPlus.
=> Enable aarch64 linux bundling OpenJCEPlus

closed/src/java.base/share/classes/java/lang/ref/NativeReferenceQueue.java
`ReferenceQueue(int)` simply delegates to `ReferenceQueue()`: this change will allow the delegating constructor to be removed from OpenJ9.
Noticed while reviewing https://github.com/eclipse-openj9/openj9/pull/20694.
=> Simplify constructor of NativeReferenceQueue

test/jdk/java/lang/System/SecurityManagerWarnings.java
Related to: https://github.com/eclipse-openj9/openj9/pull/20625
Port to 24: https://github.com/ibmruntimes/openj9-openjdk-jdk24/pull/1
=> Update SecurityManagerWarnings to match OpenJ9 stack trace

test/jdk/ProblemList-FIPS140_3_OpenJCEPlusFIPS.FIPS140-3.txt
- Exclude ExtensiblePolicyWithJarTest for FIPS140_3_OpenJCEPlusFIPS.FIPS140-3
related: https://github.ibm.com/runtimes/automation/issues/170
=> Exclude ExtensiblePolicyWithJarTest for FIPS Strict

make/common/modules/LauncherCommon.gmk
It is still needed on AIX (at least).
=> Restore use of LIBZ_LIBS when linking launchers

src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/SunPKCS11.java
Reverting a previous commit (8ddd8d766221c1ac26455512698bcf58d6e24a1c) that added support for EC aliases in KeyFactory and KeyPairGenerator for SunPKCS11.
This was previously supported in Java 8 on Z by the IBMPKCS11Impl provider. However, an openjdk contributer noted that OID is not commonly used for the KeyFactory and KeyGenerator services. Instead, the standard "EC" string should be used as an input to generate EC keys.
Given the upstream stance, no requests for continuing this support, and the availability of an alternative, this change should be removed.
=> Remove support for EC aliases in SunPKCS11

closed/DDR.gmk, closed/GensrcJ9JCL.gmk, closed/custom/Main.gmk
The solution to https://github.com/eclipse-openj9/openj9/issues/20938 will require version-specific DDR code. This prepares the foundation for upcoming changes in OpenJ9.
Create a second copy suitable for use with the boot JDK.
Delay DDR compile_check to use the exploded JDK.
=> Allow use of conditional code in DDR tools

closed/GensrcJ9JCL.gmk, src/java.base/share/classes/jdk/internal/ref/CleanerImpl.java
CRIU adds `@NotCheckpointSafe` for `CleanerImpl.CleanableList.insert()`
Removed `jdk/internal/ref/PhantomCleanable.java` from `COPY_OVERLAY_FILES` list which only applies to JDK21 and earlier versions due to the change of `CleanerImpl.CleanableList` since JDK24.
Related to
* https://github.com/eclipse-openj9/openj9/issues/21111
=> CRIU adds @NotCheckpointSafe for CleanerImpl.CleanableList.insert()

test/hotspot/jtreg/serviceability/jvmti/events/MonitorWaited/monitorwaited01/libmonitorwaited01.cpp, test/hotspot/jtreg/serviceability/jvmti/vthread/VThreadEventTest/libVThreadEventTest.cpp
OpenJ9 has its own implementation of virtual threads in the JVM.
Due to differences in implementation, the `monitorwaited01` and
`VThreadEventTest` tests have been updated to check the function names
used in OpenJ9's virtual thread implementation.
Related: https://github.com/eclipse-openj9/openj9/issues/19191
Related: https://github.com/eclipse-openj9/openj9/issues/20707
=> Update monitorwaited01 and VThreadEventTest to work with OpenJ9

closed/DDR.gmk, closed/OpenJ9.gmk, closed/autoconf/custom-spec.gmk.in, closed/make/modules/openjceplus/Lib.gmk, closed/openssl.gmk
Adapt to upstream makefile reorganization
* [8349515: [REDO] Framework for tracing makefile inclusion and parsing](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/1b19730b3e6b04aec4ff532b17e8837889e91d70)
That change uses `INCLUDE` to detect redundant makefile includes, but conflicts with the need to export that variable to the environment for the Visual Studio compiler. Instead we now export
```
INCLUDE='$(OPENJ9_VS_INCLUDE)'
```
just before invoking `make`.
=> Update makefiles for Windows

closed/GensrcJ9JCL.gmk, src/java.base/share/classes/jdk/internal/ref/CleanerImpl.java, src/java.base/share/classes/jdk/internal/ref/PhantomCleanable.java
CRIU adds `@NotCheckpointSafe` for `PhantomCleanable` constructor
`@NotCheckpointSafe` should be added for the caller of the `synchronized` method `list.insert(this)`, i.e., `PhantomCleanable(T referent, Cleaner cleaner)`.
Related to
* https://github.com/eclipse-openj9/openj9/issues/21111
=> CRIU adds @NotCheckpointSafe for PhantomCleanable constructor

closed/custom/common/Modules-post.gmk
Otherwise, use of one of those modules leads to warnings such as this:
```
WARNING: A restricted method in java.lang.System has been called
WARNING: java.lang.System::loadLibrary has been called by com.ibm.cuda.Cuda in module openj9.cuda (jrt:/openj9.cuda)
WARNING: Use --enable-native-access=openj9.cuda to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future release unless native access is enabled
```
=> Add openj9.cuda and openj9.dtfj to NATIVE_ACCESS_MODULES

closed/custom/common/Modules-post.gmk
The openjceplus module makes use of native code which results in a warning message being printed on Java 24 and higher. This update adds the openjceplus module to the NATIVE_ACCESS_MODULES which suppresses this warning message.
Signed-off-by: Jason Katonica <katonica@us.ibm.com>
=> Add openjceplus module to NATIVE_ACCESS_MODULES

closed/src/java.base/share/classes/openj9/internal/security/RestrictedSecurity.java
Fix `selectedProfile` overridden by a `null` property `semeru.customprofile`
Resolve [an internal issue](https://github.ibm.com/runtimes/backlog/issues/1612)
=> Fix selectedProfile overridden by a null property semeru.customprofile

closed/GensrcJ9JCL.gmk, src/java.base/share/classes/jdk/internal/ref/CleanerImpl.java, src/java.base/share/classes/jdk/internal/ref/PhantomCleanable.java
CRIU adds `@NotCheckpointSafe` for `CleanerImpl.CleanableList` methods
Added `@NotCheckpointSafe` to `CleanerImpl.CleanableList` `isEmpty()`, `insert()` and `remove()`.
Related to 
* https://github.com/eclipse-openj9/openj9/issues/21111#issuecomment-2698203372
The thread `"Common-Cleaner"` entered lock: ` jdk/internal/ref/CleanerImpl$CleanableList@0x000000070A36BCE8`.
```
3XMTHREADINFO      "Common-Cleaner" J9VMThread:0x0000000000172F00, omrthread_t:0x00007F19A4186B60, java/lang/Thread:0x000000070A367470, state:R, prio=8
3XMJAVALTHREAD            (java/lang/Thread getId:0x3, isDaemon:true)
3XMJAVALTHRCCL            No Java context classloader associated with this thread
3XMTHREADINFO1            (native thread ID:0x22BCBB, native priority:0x8, native policy:UNKNOWN, vmstate:CW, vm thread …
```
=> CRIU adds @NotCheckpointSafe for CleanerImpl.CleanableList methods

closed/src/java.base/share/classes/sun/security/ec/NativeECDHKeyAgreement.java, closed/src/java.base/share/classes/sun/security/ec/NativeXDHKeyAgreement.java
A check in `engineGenerateSecret(String)` was updated in `ECDHKeyAgreement` and `XDHKeyAgreement`. The equivalent native classes (i.e., `NativeECDHKeyAgreement` and `NativeXDHKeyAgreement`) are updated to reflect that change.
=> Sync up engineGenerateSecret(String) in key agreement classes

test/hotspot/jtreg/serviceability/jvmti/vthread/StopThreadTest/StopThreadTest.java
OpenJ9 only supports a single implementation; so, the code related to the legacy locking mode has been removed.
OpenJ9 does not support the below options:
```
-XX:+UnlockExperimentalVMOptions -XX:-VMContinuations
```
The test mode that uses the above options has been removed.
Related: https://github.com/eclipse-openj9/openj9/issues/21413.
=> Modify StopThreadTest to work with OpenJ9's JEP491 implementation

closed/custom/modules/java.base/Copy-post.gmk, closed/src/java.base/share/native/libjncrypto/NativeCrypto.c
OpenSSL libraries that are bundled within the runtime are being renamed to avoid conflicts with system libraries that may have the same name. Additional updates were made to the loading logic associated with native cryptography to make use of the correct bundled version by default.
Signed-off-by: Jason Katonica <katonica@us.ibm.com>
=> Rename bundled openssl libraries

closed/DDR.gmk, closed/autoconf/custom-spec.gmk.in
A new configuration option (`--disable-java-warnings-as-errors`) was added upstream, which requires this change to the interaction with `JavaCompilation.gmk`.
Notice that this targets the openj9-staging branch - the related change is not yet in the openj9 branch.
=> Adapt to new java warning suppression mechanism

src/java.base/share/classes/java/lang/VirtualThread.java
Hide JVMTI events of VirtualThread mount() and unmount() during virtual thread mount state transitions. This matches the reference implementation's behaviour.
Issue: https://github.com/eclipse-openj9/openj9/issues/21399
=> Add @JvmtiMountTransition to VThread mount() and unmount()

test/jdk/javax/xml/crypto/dsig/PSS.java, test/jdk/javax/xml/crypto/dsig/PSSSpec.java
The mask generation function (MGF) based on a hash algo is recommended to use the same hash function as the hash function fingerprinting the message for RSA-PSS. For example
```
new PSSParameterSpec("SHA-384", "MGF1",
MGF1ParameterSpec.SHA384, 48,
PSSParameterSpec.TRAILER_FIELD_BC);
```
However the structures in [PKCS#1v2.1] allow for separate parameterization of the MGF and the message digest. For example
```
new PSSParameterSpec("SHA-384", "MGF1",
MGF1ParameterSpec.SHA512, 48,
PSSParameterSpec.TRAILER_FIELD_BC);
```
OpenJCEPlus restricts to use the same hash algo for both MGF and message digest. This will cause test failures since the tests are expecting different MGF and message digest behavior.
=> Tolerate RSA-PSS in OpenJCEPlus signature

closed/DDR.gmk
Now that the boot JDK must be at least Java 24, that package is no longer used.
=> Remove reference in DDR.gmk to jdk.internal.org.objectweb.asm

test/jdk/java/lang/Thread/virtual/SynchronizedNative.java
Increase time out for `java/lang/Thread/virtual/SynchronizedNative.java`
Related to 
* https://github.com/eclipse-openj9/openj9/issues/21727
[Timed out with default settings](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk24_j9_sanity.openjdk_x86-64_windows/37/)
[Passed with increased timeout value](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/50050/console)
FYI @tajila 
=> Increase time out for java/lang/Thread/virtual/SynchronizedNative.java

test/jdk/sun/security/krb5/NullStringToKey.java
The NullStringToKey test attempts to catch the expected IllegalArgumentException by removing the SUN and SunJCE providers. However, the service remains unexpectedly available through SunPKCS11-NSS-FIPS, OpenJCEPlus, and OpenJCEPlusFIPS, causing the test to fail. This update modifies the test to remove these additional providers during execution.
=> Update NullStringToKey test

test/jdk/java/beans/XMLDecoder/8028054/TestMethodFinder.java
Increase timeout for `java/beans/XMLDecoder/8028054/TestMethodFinder.java`
Related to 
* https://github.com/eclipse-openj9/openj9/issues/21457
=> Increase timeout for java/beans/XMLDecoder/8028054/TestMethodFinder.java

test/jdk/java/security/Security/ClassLoaderDeadlock/Deadlock.java
Increase `Deadlock` test timeout for FIPS
In weak fips mode `-Dsemeru.fips=true` `-Dsemeru.customprofile=OpenJCEPlusFIPS` there is a bit more processing to
be done during startup to load and read the FIPS profiles from the `java.security` file and setup the JCE algorithms and providers available according to the profile.
Related to 
* https://github.com/eclipse-openj9/openj9/issues/21919
=> Increase Deadlock test timeout for FIPS

test/hotspot/jtreg/serviceability/jvmti/thread/GetCurrentContendedMonitor/contmon01/contmon01.java
contmon01 intermittently fails due to a race condition between
notifyAll and JVMTI GetCurrentContendedMonitor, caused by the
asynchronous scheduling of virtual threads. After being notified, a
virtual thread may not immediately contend for the monitor, resulting
in unexpected null values from GetCurrentContendedMonitor.
To mitigate this, a controlled delay is added after the virtual
thread reaches the BLOCKED state. This provides enough time for the
thread to become contended on the monitor before inspection, making
the test behavior more deterministic.
Related: https://github.com/eclipse-openj9/openj9/issues/21647
=> Fix race between notifyAll and GetCurrentContendedMonitor

src/java.base/share/classes/java/lang/VirtualThread.java, test/hotspot/jtreg/serviceability/jvmti/thread/GetCurrentContendedMonitor/contmon01/contmon01.java
VirtualThread.BLOCKING currently maps to Thread.State.BLOCKED. This
confuses tests like StopThreadTest and contmon01, which rely on
Thread.getState() to infer if a virtual thread is fully unmounted.
However, BLOCKING is an intermediate state. Mapping it to BLOCKED can
falsely indicate that a virtual thread is unmounted, leading to
incorrect assumptions and intermittent test failures.
To prevent these false positives, BLOCKING will now return
Thread.State.RUNNABLE. This aligns with other intermediate states such
as PARKING, TIMED_PARKING, WAITING, TIMED_WAITING, and YIELDING, which
also return RUNNABLE. Treating BLOCKING similarly ensures consistency
across intermediate states.
Only VirtualThread.BLOCKED will return Thread.State.BLOCKED, which
accurately reflects a fully unmounted virtual …
=> Return Thread.State.RUNNABLE for VirtualThread.BLOCKING

test/hotspot/jtreg/serviceability/jvmti/events/MonitorWaited/monitorwaited01/libmonitorwaited01.cpp
This reverts commit 23b7bc764ca0958c202724aa378b2b1e0a48a63a.
To accommodate the recent OpenJ9 implementation change
(https://github.com/eclipse-openj9/openj9/pull/21982),
the earlier fix for the `monitorwaited` test is reverted:
https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/990.
Related: https://github.com/eclipse-openj9/openj9/issues/22031
=> Revert "Update monitorwaited test to match OpenJ9 impl"

test/jdk/ProblemList-FIPS140_3_OpenJCEPlusFIPS.FIPS140-3.txt, test/jdk/ProblemList-FIPS140_3_OpenJcePlus.txt, test/jdk/ProblemList-OpenJCEPlus.txt, test/jdk/sun/security/provider/all/Deterministic.java
The `OpenJCEPlus` is added to the list of native providers to be skipped when this test is run.
The test uses a custom `SecureRandom` instance that is actually deterministic and expects the same result, but this is not applicable in `OpenJCEPlus`, since it uses a native library that utilizes its own source of randomness.
The test is also removed from the various exclusion lists.
=> Update Deterministic test to skip OpenJCEPlus

closed/src/java.base/share/classes/openj9/internal/security/RestrictedSecurity.java
Some more characters, like `#` and `:`, need to be allowed in RestrictedSecurity profile constraints, specifically the algorithm portion.
=> Allow additional characters in RestrictedSecurity profile constraints

src/java.base/share/conf/security/java.security
In the `RestrictedSecurity` profile that includes the `OpenJCEPlusFIPS` provider, the constraints that pertain to the `HKDF` services are updated to the new implementation.
=> Update HKDF constraints in RestrictedSecurity profile

test/hotspot/jtreg/serviceability/jvmti/events/FramePop/ClearAllFramePops/libClearAllFramePops.cpp
The code should have been restored when ClearAllFramePops was stubbed via https://github.com/eclipse-openj9/openj9/pull/21168
Issue https://github.com/eclipse-openj9/openj9/issues/20980
=> Remove temp change from libClearAllFramePops.cpp

src/java.base/share/conf/security/java.security
This update adds a new FIPS 140-3 profile that enables common
configuration options for cryptography and other java services that
MAY be configured in a FIPS compliant manor depending on deployment
topology. Highlights include configuration options to enable PKCS12
keystores and associated cryptography, allowances for RMI, enablement
of the SunJGSS provider, and enablement of the JdkSASL provider.
Signed-off-by: Jason Katonica <katonica@us.ibm.com>
=>  Add new Strongly-Enforced FIPS 140-3 profile

test/jdk/ProblemList-FIPS140_2.txt, test/jdk/ProblemList-FIPS140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced.txt, test/jdk/ProblemList-FIPS140_3_OpenJCEPlusFIPS.FIPS140-3.txt, test/jdk/ProblemList-FIPS140_3_OpenJcePlus.txt
This commit updates a test in the FIPS 140-3 Strict profile exclusion list, including the full test case name.
From
`sun/security/pkcs12/KeytoolOpensslInteropTest.java`
To 
`sun/security/pkcs12/KeytoolOpensslInteropTest.java#UseExistingPKCS12`
=> Update the exclusion list for the FIPS 140-3 Strict profile

closed/src/java.base/share/classes/sun/security/ec/NativeXDHKeyAgreement.java
NativeXDHKeyAgreement is updated to support keys created from a different provider than Sun using the XDHKeyFactory.
Signed-off-by: Dev Agarwal dev.agarwal@ibm.com
=> Add compatibility for a key from a different provider

test/jdk/ProblemList-FIPS140_2.txt, test/jdk/ProblemList-FIPS140_3_OpenJCEPlusFIPS.FIPS140-3-Strongly-Enforced.txt, test/jdk/ProblemList-FIPS140_3_OpenJCEPlusFIPS.FIPS140-3.txt, test/jdk/ProblemList-FIPS140_3_OpenJcePlus.txt
This PR temporarily adds one test to the exclusion list for the FIPS tests due to an issue with the RestrictedSecurity code. The test will be removed from the exclusion list once the RestrictedSecurity issue is solved.
=> Update the exclusion list for the FIPS tests

closed/src/java.base/share/classes/sun/security/ec/NativeXDHKeyPairGenerator.java
NativeXDHKeyPairGenerator is updated to use the correct instance of XDHKeyPairGenerator for varying
curves in multithreaded environment for `generateKeyPair()` when all the threads share the same instance of KeyPairGenerator. 
Signed-off-by: Dev Agarwal <dev.agarwal@ibm.com>
=> Add thread safety for generateKeyPair in NativeXDHKeyPairGenerator

src/java.base/share/classes/jdk/internal/foreign/SegmentFactories.java
Fix for Issue eclipse-openj9/openj9#22219
Ensure minimum allocation size of Long.BYTES.
initNativeMemory() writes a full long (Long.BYTES). 
1-byte allocation is not enough and can corrupt the footer added by OMR.
=> Fix minimum allocation size

src/java.base/share/classes/java/lang/Thread.java
depend: https://github.com/eclipse-openj9/openj9/pull/21043
Rework of https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/879
=> Update getState() API to use holder.threadStatus field

src/java.desktop/unix/classes/sun/print/PrintServiceLookupProvider.java
The initialization was accidently removed by
https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/30e8e0763b
=> Init results in PrintServiceLookupProvider.execCmd
